[package]
name = "template_engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - template_engine"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "template_engine" ]
publish.workspace = true

[dependencies]
## Template engine
tera = "1.20.0"
tinytemplate = "1.2.1"

## General
anyhow.workspace = true
#async-trait.workspace = true
#lazy_static.workspace = true
#ndarray.workspace = true
#once_cell.workspace = true
#rand.workspace = true
serde.workspace = true
#serde_json.workspace = true
#tokio.workspace = true
#tracing.workspace = true
#tracing-subscriber.workspace = true
