[package]
name = "development_tools_ffi"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - development_tools_ffi"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "development_tools_ffi" ] # TODO P1
publish.workspace = true

[dependencies]
cxx = "1.0.136"
jni = "0.21.1"
uniffi = "0.28.3"
rustler = "0.36.0"

[build-dependencies]
bindgen = "0.71.1"
cbindgen = "0.28.0"
cc = "1.2"
cxx-build = "1.0.136"
uniffi = "0.28.3"
