[package]
name = "concurrency"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - concurrency"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["concurrency"]
publish.workspace = true
autolib = false

[dependencies]
actix = "0.13.5"

## General
anyhow = "1.0.102"
await-tree = { version = "0.3.1", features = ["tokio"] }
clap = { version = "4.6.1", features = ["derive"] }
crossbeam = "0.8.4"
crossbeam-channel = "0.5.15"
crossbeam-queue = "0.3.12"
crossbeam-utils = "0.8.21"
dashmap = "6.1.0"
flume = { version = "0.12.0", features = ["select"] }
flurry = "0.5.2"
futures = "0.3.32"
glob = "0.3.3"
image = "0.25.10"
itertools = "0.14.0"
lazy_static = "1.5.0"
num = "0.4.3"
num_cpus = "1.17.0"
papaya = "0.2.4"
parking_lot = "0.12.5"
ractor = "0.15.12"
rand = { version = "0.10.1", features = ["thread_rng"] }
rayon = "1.12.0"
riker = "0.4.2"
ring = "0.17.14"
stakker = "0.2.15"
threadpool = "1.8.1"
time = "0.3.47"
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread"] }
walkdir = "2.5.0"

[[example]]
name = "actors"
path = "examples/actors/main.rs"
test = true

[[example]]
name = "atomics"
path = "examples/atomics/main.rs"
test = true

[[example]]
name = "await_tree"
path = "examples/await_tree.rs"
test = true

[[example]]
name = "concurrent_data_structures"
path = "examples/concurrent_data_structures/main.rs"
test = true

[[example]]
name = "crossbeam"
path = "examples/crossbeam/main.rs"
test = true

[[example]]
name = "data_parallelism"
path = "examples/data_parallelism/main.rs"
test = true

[[example]]
name = "explicit_threads"
path = "examples/explicit_threads/main.rs"
test = true

[[example]]
name = "message_passing"
path = "examples/message_passing/main.rs"
test = true

[[example]]
name = "send_sync"
path = "examples/send_sync/main.rs"
test = true

[[example]]
name = "shared_state"
path = "examples/shared_state/main.rs"
test = true

[[example]]
name = "threadpool"
path = "examples/threadpool/main.rs"
test = true
