[package]
name = "development_tools_debugging"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - development_tools_debugging"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["development_tools_debugging"]
publish.workspace = true

[dependencies]
## Dev Tools: Debugging
env_logger = "0.11.6"
log = "0.4.22"
log4rs = "1.3.0"
opentelemetry = "0.27.1"
opentelemetry-jaeger = "0.22.0"
opentelemetry-otlp = "0.27.0"
opentelemetry_sdk = { version = "0.27.1", features = ["metrics"] }
opentelemetry-semantic-conventions = "0.27.0"
tonic = "0.12.3"
tracing.workspace = true
tracing-opentelemetry = "0.28.0"
tracing-subscriber.workspace = true

## General
axum = "0.8.1"
dotenvy = "0.15.7"
serde_json.workspace = true

anyhow.workspace = true
crates-io = "0.40.6"
dashmap = "6.1.0"
data-encoding = "2.6.0"
glob = "0.3.1"
hex-literal = "0.4"
hyper = "1.5.2"
hyper-tls = "0.6.0"
image = "0.25.5"
itertools = "0.14.0"
lazy_static.workspace = true
num = "0.4.3"
num_cpus = "1.16.0"
rand.workspace = true        # use beta
serde.workspace = true
serde_derive = "1.0.216"
time = "0.3.37"
tokio.workspace = true
walkdir.workspace = true
chrono = "0.4.39"


[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10.68", features = ["vendored"] }
rusqlite = { version = "0.32.1", features = ["chrono"] }
syslog = "7.0.0"

[dev-dependencies]
## Used for testing
rusty-fork = "0.3.0"
