[package]
name = "development_tools_debugging"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - development_tools_debugging"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["development_tools_debugging"]
publish.workspace = true

[dependencies]
env_logger = "0.11.6"
log = "0.4.22"
log4rs = "1.3.0"
opentelemetry = "0.27.1"
opentelemetry-jaeger = "0.22.0"
opentelemetry-otlp = "0.27.0"
opentelemetry_sdk = { version = "0.27.1", features = ["metrics"] }
opentelemetry-semantic-conventions = "0.27.0"
tonic = "0.12.3"
tracing.workspace = true
tracing-opentelemetry = "0.28.0"
tracing-subscriber.workspace = true

## General
anyhow.workspace = true
axum = "0.8.1"
chrono = "0.4.39"
serde_json.workspace = true
tokio.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10.68", features = ["vendored"] }
rusqlite = { version = "0.32.1", features = ["chrono"] } # pinned
syslog = "7.0.0"

[dev-dependencies]
## Used for testing
rusty-fork = "0.3.0"
