[package]
name = "science"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - science"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["science"]
publish.workspace = true
autolib = false

[dependencies]
## Machine Learning
candle-core = "0.9.1"
# candle-datasets = "0.8.2"
# candle-examples = "0.8.1"
candle-nn = "0.9.1"
# candle-onnx = "0.8.2"
# candle-pyo3 = "0.8.2"
# candle-transformers = "0.8.2"
linfa = "0.7.0"
linfa-linear = "0.7.0"
ndarray = "0.15.6" # pinned to 0.15.6 for linfa
rand = { version = "0.9.0", features = ["thread_rng"] }
smartcore = { version = "0.4.0", features = ["datasets"] }

[features]
#default = []
#candle = ["dep:candle-core", "dep:candle-nn"]
