[package]
name = "multimedia_video"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - multimedia_video"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = [ "multimedia::video" ]
publish.workspace = true
autolib = false

[dependencies]
av-scenechange = { version = "0.23.0", default-features = false }
