[package]
name = "stream_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
futures = "0.3.29"
reqwest = "0.11.22"
thiserror = "1.0.50"
tokio = { version = "1.35.0", features = ["full"] }
