[package]
name = "parsing"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - parsing"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["parsing"]
publish.workspace = true
autolib = false

[package.metadata.cargo-machete]
ignored = ["pest_generator"]

[dependencies]
anyhow = "1.0.100"
nom = "8.0.0"
pest = "2.8.3"
pest_derive = "2.8.3"
tree-sitter = "0.25.1"
tree-sitter-rust = "0.24.0"
winnow = "0.7.1"

[build-dependencies]
pest_generator = "2.8.3"
