[package]
name = "parsing"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - parsing"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["parsing"]
publish.workspace = true
autolib = false

[package.metadata.cargo-machete]
ignored = ["pest_generator"]

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
nom = "8.0.0"
pest = "2.8.6"
pest_derive = "2.8.6"
tree-sitter = "0.26.8"
tree-sitter-rust = "0.24.2"
winnow = "1.0.2"

[build-dependencies]
pest_generator = "2.8.6"

[[example]]
name = "parsing"
path = "examples/parsing/main.rs"
test = true

[[example]]
name = "pest"
path = "examples/pest/main.rs"
test = true
