[package]
name = "parsing"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - parsing"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["parsing"]
publish.workspace = true
autolib = false

# FIXME
[dependencies]
# binascii = "0.1.4"
nom = "8.0.0"
pest = "2.7.15"
pest_derive = "2.7.15"
# tree-sitter = "0.25.1"
# tree-sitter-rust = "0.24.0"

[build-dependencies]
pest_generator = "2.7.15"
# cc = "1.2"

# FIXME
# [features]
# default = []
# pest = ["dep:pest", "dep:pest_derive", "dep:pest_generator"]

[package.metadata.cargo-machete]
ignored = ["pest_generator"]
