#![allow(dead_code)]
// ANCHOR: example
//! This example demonstrates reading and writing Cap'n Proto
//! messages. It is intended to be used in conjunction with code
//! generated by the `capnpc-rust` crate.
//!
//! Add the following dependencies to your `Cargo.toml`:
//! ```toml
//! [dependencies]
//! capnp = "0.20.3"
//! [build-dependencies]
//! capnpc = "0.20.1"
//! ```
//!
//! Make sure the following lines are in your `build.rs` file:
//! ```rust
//! fn main() {
//!     capnpc::CompilerCommand::new()
//!         .file("examples/binary_encoders/foo.capnp")
//!         .run()
//!         .expect("schema compiler command");
//! }
//! ```

use capnp::message::Builder;
use capnp::serialize;

/// Define the module for the generated code.
pub mod foo_capnp {
    // The `capnpc` compiler generates a file named [filename]_capnp.rs.
    include!(concat!(env!("OUT_DIR"), "/foo_capnp.rs"));
}

fn main() {
    // 1. Create a message builder (the container for the data).
    let mut message = Builder::new_default();

    {
        // 2. Initialize the root object using the generated Builder type for 'MyStruct'.
        let mut my_struct = message.init_root::<foo_capnp::my_struct::Builder>();

        // 3. Set values on the fields.
        my_struct.set_name("Hello from Rust");
        my_struct.set_value(42);
    }

    // 4. Serialize the message into a byte buffer.
    let mut write_buffer = Vec::new();
    serialize::write_message(&mut write_buffer, &message).expect("Failed to serialize message");

    println!("Cap'n Proto message serialized. Size: {} bytes", write_buffer.len());
}

#[test]
fn test_capnp_serialization() {
    main();
}
// ANCHOR_END: example

/// Entry point to run the Cap'n Proto example.
pub fn run() {
    main();
}
