[package]
license-file.workspace = true
name = "web_programming_websocket"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples for Web Programming with WebSockets using Tungstenite."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["websocket", "networking", "tungstenite", "tokio", "async"]
categories = ["web-programming::websocket"]
publish.workspace = true
autolib = false

[dependencies]
anyhow = "1.0.102"
async-tungstenite = { version = "0.34.1", features = [
    "tokio-runtime",
    "tokio-native-tls",
] }
futures-util = "0.3.32"
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread", "net"] }
tokio-tungstenite = "0.29.0"
tungstenite = "0.29.0"

[[example]]
name = "websocket"
path = "examples/websocket/main.rs"
test = true
