[package]
license-file.workspace = true
name = "no_std_no_alloc"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - no_std_no_alloc"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["no-std::no-alloc"]
publish.workspace = true
autolib = false

[dependencies]

[[example]]
name = "no_alloc"
path = "examples/no_alloc/main.rs"
test = true
