[package]
name = "memory_management"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Examples of advanced memory management, allocators, and data structures like Slab and Bumpalo."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["memory", "allocators", "bumpalo", "mimalloc", "slab", "optimization"]
categories = ["memory-management"]
publish.workspace = true
autolib = false

[dependencies]
anyhow = "1.0.102"
bumpalo = "3.20.2"
clap = { version = "4.6.1", features = ["derive"] }
lazy_static = "1.5.0"
mimalloc = "0.1.50"
once_cell = "1.21.4"
seize = "0.5.1"
slab = "0.4.12"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemalloc-ctl = { version = "0.6.1", features = ["stats", "use_std"] }
tikv-jemallocator = "0.6.1"

[[example]]
name = "bumpalo"
path = "examples/bumpalo.rs"
test = true

[[example]]
name = "jemalloc"
path = "examples/jemalloc.rs"
test = true

[[example]]
name = "lazy_initialization"
path = "examples/lazy_initialization/main.rs"
test = true

[[example]]
name = "mimalloc"
path = "examples/mimalloc.rs"
test = true

[[example]]
name = "seize"
path = "examples/seize.rs"
test = true

[[example]]
name = "slab"
path = "examples/slab.rs"
test = true
