## General
anyhow.workspace = true
bytes = "1.9.0"
lazy_static.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
regex.workspace = true
futures-util = "0.3.31"
