[package]
name = "data_structures"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - data_structures"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "data_structures" ]
publish.workspace = true

[dependencies]
arrayvec = "0.7.6"
bitflags = "2.6.0"
bytes = "1.9.0"
dashmap = "6.1.0"
flagset = "0.4.6"
indexmap = "2.7.0"
linked-hash-map = "0.5.6"
multimap = "0.10.0"
#petgraph = "0.7.0" # TODO P2
slotmap = "1.0.7"
smallvec = "2.0.0-alpha.8" # alpha
tinyvec = { version = "1.8.1", features = ["alloc"] }
uuid = { version = "1.11.0", features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
] }

## General
anyhow.workspace = true
crates_io_api = "0.11.0"
