[package]
name = "stuv"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - categories S to V"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

## Science - Machine Learning
candle-core = "0.8.2"
candle-nn = "0.8.2"
linfa = "0.7.0"
linfa-linear = "0.7.0"
smartcore = { version = "0.4.0", features = [ "datasets" ] }

## Science - Robotics
bonsai-bt = "0.8.0"
openrr = "0.1.0" # requires `libudev-dev` TODO
urdf-rs = "0.9.0"
zenoh = "1.0.2"

## Template engine
tera = "1.20.0"
tinytemplate = "1.2.1"

## Text processing
concat-string = "1.0.1"
fancy-regex = "0.14.0"
joinery = "3.1.0"
regex.workspace = true
unicode-segmentation = "1.12.0"

## Value formatting
# TODO

## Virtualization
# TODO wasmi

## Visualization
plotly = "0.12.1"

## General
anyhow.workspace = true
async-trait.workspace = true
lazy_static.workspace = true
once_cell.workspace = true
ndarray.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
