[package]
name = "stuv"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - categories S to V"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## The dependencies that are NOT USED (YET) in examples are marked `optional = true`,
## in order to keep the compile speed decent.
## Remove the optional flag as needed.
[dependencies]

## Science - Machine Learning
candle-core = { version = "0.8.1", git = "https://github.com/huggingface/candle.git" }
linfa = "0.7.0"
linfa-linear = "0.7.0"
smartcore = "0.4.0"
watchmaker = { version = "2.0.0", optional = true }

## Science - Robotics
openrr = { version = "0.1.0", optional = true } # requires `libudev-dev`
zenoh = { version = "1.0.2", optional = true }

## Template engine
# TODO

## Text processing
concat-string = "1.0.1"
fancy-regex = "0.14.0"
joinery = "3.1.0"
regex = "1.11.1"
unicode-segmentation = "1.12.0"

## Value formatting
# TODO

## Virtualization
# TODO

## Visualization
plotly = { version = "0.12.1", optional = true }

## General
anyhow = "1.0.91"
lazy_static = "1.5.0"
once_cell = "1.20.2"
ndarray = "0.15.6"
