[package]
name = "filesystem"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - filesystem"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "filesystem" ]
publish.workspace = true

[dependencies]
anyhow.workspace = true
directories = "6.0.0"
dirs = "6.0.0"
glob = "0.3.1"
globset = "0.4.15"
ignore = "0.4.23"
memmap2 = "0.9.5"
notify = "8.0.0"
open = "5.3.0"
remove_dir_all = "1.0.0"
same-file = "1.0.6"
# tempdir = "0.3.7" # Outdated, replaced by tempfile
tempfile = "3.14.0"
walkdir.workspace = true
