[workspace]

members = [
    # project that contains most code examples in the book - see `examples` folder
    "deps",
    # examples independent from the book markdown
    "xmpl/*",
    # utilities to build the book
    "utils"
]
# Only check / build the main crate by default (check / build all with `--workspace`)
default-members = ["deps"]
exclude = []
resolver = "2"
