[workspace]

members = [
    # stub project to declare the dependencies of the code embedded in the markdown
    "deps",
    # examples independent from the book markdown
    "xmpl/*"
]
# Only check / build main crate by default (check all with `--workspace`)
default-members = ["deps"]
exclude = []
resolver = "2"
