[package]
name = "os_windows_apis"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - os_windows_apis"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["os_windows_apis"]
publish.workspace = true
autolib = false

[dependencies]

[target.'cfg(target_os = "windows")'.dependencies]
# [native-windows-gui: review pre-requisites](https://github.com/john-cd/rust_howto/issues/1305)
# native-windows-gui = "1.0.13"
# native-windows-derive = "1.0.3" # Required only if the derive macro is used.
winapi = { version = "0.3.9", features = ["winuser"] }
windows = { version = "0.61.1" }
