[package]
name = "cryptography"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - cryptography"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["cryptography"]
publish.workspace = true

[dependencies]
## Crypto
aes-gcm-siv = "0.11.1"
aes-gcm = "0.10.3"
argon2 = "0.5.3"
bcrypt = "0.16.0"
blake3 = "1.5.5"
chacha20poly1305 = "0.10.1"
# curve25519-dalek = "4.1.3" # TODO P2
der = { version = "0.7.9", features = ["derive", "alloc"] }
dsa = "0.6.3"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
ecdsa = "0.16.9"
md5 = "0.7.0"
native-tls = "0.2.12"
p256 = "0.13.2"
pem-rfc7468 = "0.7.0"
pkcs8 = "0.10.2"
ring = "0.17.8"
rsa = "0.9.7"
rustls = "0.23.20"
scrypt = "0.11.0"
sha1 = "0.10.6"
sha2 = "0.10.8"
subtle = "2.6.1"
tokio-rustls = "0.26.1"
x509-cert = "0.2.5"
zeroize = "1.8.1"

## General
anyhow.workspace = true
#chrono = "0.4.39"
#crates-io = "0.40.6"
#dashmap = "6.1.0"
data-encoding = "2.6.0"
#glob = "0.3.1"
#hex-literal = "0.4"
#hyper = "1.5.2"
#hyper-tls = "0.6.0"
#image = "0.25.5"
#itertools = "0.14.0"
#lazy_static.workspace = true
#num = "0.4.3"
#num_cpus = "1.16.0"
rand.workspace = true        # use beta
#serde.workspace = true
#serde_derive = "1.0.216"
#time = "0.3.37"
#tokio.workspace = true
#walkdir.workspace = true
