[package]
name = "asynchronous"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - asynchronous"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["asynchronous"]
publish.workspace = true

[dependencies]
async-channel = "2.3.1"
# async-std = "1.13.0"
# async-stream = "0.3.6"
async-trait = "0.1.85"
duct = "0.13.7"
futures = "0.3.31"
futures-executor = "0.3.31"
kanal = "0.1.0-pre8"                                # NOTE: pre version
mio = "1.0.2"
parking_lot = "0.12.3"
postage = "0.5.0"
rayon = "1.10.0"
reqwest = "0.12.12"
smol = "2.0.2"
tokio = { version = "1.43.0", features = ["full"] }
tokio-graceful-shutdown = "0.15.2"

## General
anyhow = "1.0.95"
rand = { version = "0.9.0", features = ["thread_rng"] }
time = "0.3.37"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[features]
# default = []
