[package]
name = "asynchronous"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - asynchronous"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "asynchronous" ]
publish.workspace = true

[dependencies]
## Async
async-channel = "2.3.1"
# async-std = "1.13.0"
# async-stream = "0.3.6"
async-trait.workspace = true
duct = "0.13.7"
futures = "0.3.31"
futures-executor = "0.3.31"
kanal = "0.1.0-pre8" # NOTE: pre version
mio = "1.0.2"
parking_lot = "0.12.3"
postage = "0.5.0"
rayon = "1.10.0"
reqwest.workspace = true
smol = "2.0.2"
tokio.workspace = true
tokio-graceful-shutdown = "0.15.2"

## General
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

## General
# chrono = "0.4.39"
#crates-io = "0.40.6"
#dashmap = "6.1.0"
#data-encoding = "2.6.0"
#glob = "0.3.1"
#hex-literal = "0.4"
#hyper = "1.5.2"
#hyper-tls = "0.6.0"
#image = "0.25.5"
#itertools = "0.14.0"
#lazy_static.workspace = true
#num = "0.4.3"
#num_cpus = "1.16.0"
rand.workspace = true
#serde.workspace = true
#serde_derive = "1.0.216"
#tempfile = "3.14.0"
time = "0.3.37"
#walkdir.workspace = true
