[workspace]
resolver = "3"
members = ["cancelable", "clap_builder_xmpl"]

# Default values for packages in the workspace
[workspace.package]
version = "0.1.2"
authors = ["John CD"]
edition = "2024"
rust-version = "1.90"
description = "A collection of standalone, ready-to-run Rust code examples for various programming domains."
documentation = "https://docs.rs/rust_howto/"
homepage = "https://john-cd.com/rust_howto/"
repository = "https://github.com/john-cd/rust_howto/xmpl/"
keywords = ["examples", "rust-by-example", "tutorial", "reference"]
categories = ["asynchronous", "command-line-utilities"]
publish = false
