[package]
name = "concurrency"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - concurrency"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["concurrency"]
publish.workspace = true

[dependencies]
actix = "0.13.5"
await-tree = "0.2.1"
crossbeam = "0.8.4"
crossbeam-channel = "0.5.14"
crossbeam-queue = "0.3.12"
crossbeam-utils = "0.8.21"
dashmap = "6.1.0"
flume = { version = "0.11.1", features = ["select"] }
flurry = "0.5.2"
futures = "0.3.31"
parking_lot = "0.12.3"
ractor = "0.14.2"
rayon = "1.10.0"
riker = "0.4.2"
stakker = "0.2.11"
threadpool = "1.8.1"

## General
anyhow.workspace = true
glob = "0.3.1"
image = "0.25.5"
itertools = "0.14.0"
lazy_static.workspace = true
num = "0.4.3"
num_cpus = "1.16.0"
rand.workspace = true
ring = "0.17.8"
time = "0.3.37"
tokio.workspace = true
walkdir.workspace = true
