mod multithreading_rayon;
mod multithreading_rayon_custom;
mod multithreading_rayon_parsort;
mod rayon_any_all;
mod rayon_iter_mut;
mod rayon_map_reduce;
mod rayon_parallel_search;
mod rayon_parallel_sort;
mod rayon_thumbnails;
