[package]
name = "deps" # All crate DEPendencies for the book's examples are stored below.
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
#license.workspace = true
#license-file.workspace = true
keywords.workspace = true
categories.workspace = true
workspace = ".."
build = "build.rs"
#exclude.workspace = true
#include.workspace = true
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
anyhow = "1"
approx = "0.5"
async-trait = "0.1"
base64 = "0.21"
bitflags = "2"
byteorder = "1"
bytes = "1"
cc = "1"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
#clap-verbosity-flag = "2.1"
concat-string = "1"
concat_strs = "1"
confy = "0.6"
crossbeam = "0.8"
crossbeam-channel = "0.5"
crossbeam-queue = "0.3"
crossbeam-utils = "0.8"
csv = "1"
dashmap = "5"
data-encoding = "2"
derive_more = "0.99"
#doc-comment = "0.3"
dotenvy = "0.15"
env_logger = "0.11"
envy = "0.4"
flate2 = "1"
futures = "0.3"
glob = "0.3"
http = "1"
http-body-util = "0.1"
image = "0.24"
lazy_static = "1"
log = "0.4"
log4rs = "1"
memmap = "0.7"
miette = { version = "7", features = ["fancy"] }
mime = "0.3"
nalgebra = { version = "0.32", features = ["serde-serialize"] }
ndarray = { version = "0.15", features = ["approx"] }
notify = "6"
num = "0.4"
num_cpus = "1"
once_cell = "1"
# openssl = { version = "0.10", features = ["vendored"] }
parking_lot = "0.12"
percent-encoding = "2"
#petgraph = "0.6"
postgres = "0.19"
rand = "0.8"
rand_distr = "0.4"
rayon = "1"
regex = "1"
reqwest = { version = "0.11", features = ["blocking", "json", "stream"] }
ring = "0.17"
rusqlite = { version = "0.31", features = ["chrono"] }
same-file = "1"
#sea-orm = "0.12"
select = "0.6"
semver = "1"
serde = { version = "1", features = ["derive"] }
#serde_derive = "1"
serde_json = "1"
tar = "0.4"
tempfile = "3"
thiserror = "1"
threadpool = "1"
tokio = { version = "1", features = ["full"] }
tokio-graceful-shutdown = "0.14"
toml = "0.8"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["full", "auth"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
unicode-segmentation = "1"
url = "2"
walkdir = "2"
#build-info = "0.0.34"

[target.'cfg(target_os = "linux")'.dependencies]
syslog = "6"

[build-dependencies]
anyhow = "1"
#build-info-build = "0.0.34"
# The git dependency will be used locally; when published to a registry like crates.io, it will use the registry version.
mdbook-utils = { git = 'https://github.com/john-cd/mdbook-utils.git', version = "0.*" }
skeptic = "0.13"
walkdir = "2"

[dev-dependencies]
skeptic = "0.13"
