[package]
name = "dependencies"
edition = "2024"

[dependencies]

## `cargo-husky` handles git hook scripts
[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["user-hooks"]
## Note that, when user-hooks feature is enabled, other all features are disabled.
## You need to prepare all hooks in .cargo-husky/hooks directory.
## See https://lib.rs/crates/cargo-husky
