[package]
name = "dependencies"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "All book code examples and their crate DEPendencieS"
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
workspace = ".."
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## The following serves as the master list of crates mentioned in the book.
##
## The dependencies that are NOT USED (YET) in examples are marked `optional = true`,
## in order to keep the compile speed decent.
## Remove the optional flag as needed.
[dependencies]
accesskit = { version = "0.17.0", optional = true }
actix-web = { version = "4.9.0", optional = true }
ansi_term = "0.12.1"                                # NOTE: unmaintained
anyhow = "1.0.91"
approx = "0.5.1"
arrow = "53.2.0"
async-channel = "2.3.1"
async-std = "1.13.0"
async-stream = "0.3.6"
async-trait = "0.1.83"
axum = { version = "0.7.7", optional = true }
# bacon = { version = "3.2.0", optional = true }
base64 = "0.22.1"
# bat
bevy = { version = "0.15.0", optional = true }
bitflags = "2.6.0"
# broot
build-info = { version = "0.0.39", optional = true }
byteorder = "1.5.0"
bytes = "1.8.0"
candle-core = { version = "0.8", optional = true }
# cargo
# cargo-auditable
# cargo-cache
# cargo-edit
# cargo-hack
# cargo-husky
# cargo-make
# cargo-nextest
# cargo-tarpaulin
# cargo-udeps
cc = "1.2.1"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
clap-verbosity-flag = "3.0.0"
concat-string = "1.0.1"
concat_strs = "1.0.2"
confy = "0.6.1"
cornucopia = { version = "0.9.0", optional = true }
cosmic-text = { version = "0.12.1", optional = true }
crates_io_api = "0.11.0"
cross = { version = "0.2.5", optional = true }
crossbeam = "0.8.4"
crossbeam-channel = "0.5.13"
crossbeam-queue = "0.3.11"
crossbeam-utils = "0.8.20"
crux_core = { version = "0.10.0", optional = true }
csv = "1.3.0"
curve25519-dalek = "4.1.3"                               # security update
dashmap = "6.1.0"
data-encoding = "2.6.0"
datafusion = { version = "43.0.0", optional = true }
derive_more = { version = "1.0.0", features = ["full"] }
diesel = { version = "2.2.4", optional = true }
digest = "0.10.7"
doc-comment = "0.3"
# dotenv = "0.15.0" # outdated, replaced by dotenvy
dotenvy = "0.15.7"
# druid = { version = "0.8.3", optional = true } # TODO P3 review conflicts
duct = { version = "0.13.7", optional = true }
dyn-clone = "1.0.17"
ed25519-dalek = "2.0"                                           # security update
egui = { version = "0.29.1", optional = true }
elasticsearch = { version = "8.15.0-alpha.1", optional = true } # NOTE: alpha version
# embassy = { version = "0.0.0", optional  = true } # TODO P1 review installation / required dependencies
env_logger = "0.11.5"
envy = "0.4.2"
# exa = { version = "0.10.1", optional = true } # TODO P3 review conflicts
# eyre = "0.6.12" # outdated, see color-eyre
flagset = "0.4.6"
flate2 = "1.0.34"
# floem = { version = "0.1.1", optional  = true } # TODO P3 review requirements
form_urlencoded = { version = "1.2.1", optional = true }
futures = "0.3.31"
futures-executor = "0.3.31"
git2 = "0.16.1"                                          # security update
glidesort = { version = "0.1.2", optional = true }
glob = "0.3.1"
globset = { version = "0.4.15", optional = true }
gping = { version = "1.17.3", optional = true }
http = "1.1.0"
http-body-util = "0.1.2"
hyper = { version = "1.5.0", optional = true }
iced = { version = "0.13.1", optional = true }
image = "0.25.4"
indicatif = { version = "0.17.8", optional = true }
infisearch = { version = "0.10.1", optional = true }
itertools = "0.13.0"
just = "1.36.0"
# kanal = { version = "0.1.0-pre8", optional = true } # NOTE: pre version
kani = { version = "0.0.1", optional = true }
lazy_static = "1.5.0"
# lens
leptos = { version = "0.7.0-gamma3", optional = true }
lettre = "0.11.10"
# libgit2-sys = "0.16.2" # sec advisory to upgrade to 0.16.2+; currently conflicts with pyoxidizer
linfa = { version = "0.7.0", optional = true }
linked-hash-map = "0.5.6"
loco = { version = "0.13.2", optional = true }
log = "0.4.22"
log4rs = "1.3.0"
lru = "0.12.5"
# lsd
# mdbook
# mdbook-cmdrun
# mdbook-journal
# mdbook-keeper
# mdbook-linkcheck
# mdbook-pagetoc
# mdbook-private
# mdbook-tera
# mdbook-theme
# mdbook-toc
meilisearch = { version = "0.0.0", optional = true }
memmap2 = "0.9.5"
miette = { version = "7.2.0", features = ["fancy"] }
mime = "0.3.17"
minisearch = { version = "0.1.1", optional = true }
mio = { version = "1.0.2", optional = true }
# miri
mongodb = { version = "3.1.0", optional = true }
monostate = { version = "0.1.13", optional = true }
multimap = "0.10.0"
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
# native-windows-gui = { version = "1.0.13", optional = true }   # TODO P3 review pre-requisites
# native-windows-derive = { version = "1.0.3", optional = true } # Required only if the derive macro is used.
ndarray = { version = "0.16.1", features = ["approx"] }
nom = { version = "7.1.3", optional = true }
notify = "7.0.0"
num = "0.4.3"
num_cpus = "1.16.0"
once_cell = "1.20.2"
open = { version = "5.3.0", optional = true }
opencv = { version = "0.93.3", optional = true }                            # requires `libopencv-dev` `clang` `libclang-dev`
openrr = { version = "0.1.0", optional = true }                             # requires `libudev-dev`
openssl = { version = "0.10", features = ["vendored"] }
parking_lot = "0.12.3"
paste = { version = "1.0.15", optional = true }
percent-encoding = "2.3.1"
pest = { version = "2.7.14", optional = true }
petgraph = { version = "0.6", optional = true }
plotly = { version = "0.10.0", optional = true }
polars = { version = "0.44.2", optional = true }
postscript = { version = "0.18.2", optional = true }
postage = { version = "0.5.0", optional = true }
postgres = "0.19.9"
proc-macro2 = { version = "1.0.89", optional = true }
pyo3 = "0.21"                                                               # pinned to 0.21 to avoid conflict with `polars`
pyoxidizer = { version = "0.24.0", optional = true }
quote = { version = "1.0.37", optional = true }
r3bl_tuify = { version = "0.2.0", optional = true }
rand = "0.8.5"
rand_distr = "0.4.3"
ratatui = "0.29.0"
rayon = "1.10.0"
redis = "0.27.5"
regex = "1.11.1"
remove_dir_all = { version = "1.0.0", optional = true }
reqwest = { version = "0.12.9", features = ["blocking", "json", "stream"] }
rhai = { version = "1.19.0", optional = true }
riker = { version = "0.4.2", optional = true }
ring = "0.17.8"
# roogle = "1.0.0" # not a lib
# ruff = "0.0.1" # not a lib
# rui = "0.6.1" # experimental at this point
rusqlite = { version = "0.32.1", features = ["chrono"] }
# rustdesk = { version = "0.1.1", optional = true } # app
rust_cache = { version = "0.3.0", optional = true }
RustQuant = { version = "0.3", optional = true }
salsa = { version = "0.16.1", optional = true }
same-file = "1.0.6"
sea-orm = { version = "1.1.1", optional = true }
seaography = { version = "1.1.0", optional = true }
select = "0.6.0"
semver = "1.0.23"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
sled = { version = "0.34.7", optional = true }
slint = { version = "1.8.0", optional = true }
slotmap = { version = "1.0.7", optional = true }
smol = { version = "2.0.2", optional = true }
sqlx = "0.8.2"
stakker = { version = "0.2.11", optional = true }
starship = { version = "1.21.1", optional = true }
# stork-search = "1.6.0" # not a lib
swc_ecma_parser = { version = "6.0.0", optional = true }
syn = { version = "2.0.87", optional = true }
tantivy = { version = "0.22.0", optional = true }
tar = "0.4.42"
tauri = { version = "2.0.6", optional = true }           # requires multiple libraries. See Dockerfile
# tempdir = "0.3.7" # outdated, replaced by tempfile
tempfile = "3.14.0"
# termbook = "1.4.2" # requires mdbook; TODO P3 review pre-requisites
thiserror = "2.0.1"
threadpool = "1.8.1"
time = "0.3.36"
tinysearch = { version = "0.8.2", optional = true }
tokio = { version = "1.41.1", features = ["full"] }
tokio-graceful-shutdown = "0.15.1"
toml = "0.8.19"
tonic = { version = "0.12.3", optional = true }
tower = { version = "0.5.1", features = ["util"] }
tower-http = { version = "0.6.1", features = ["full", "auth"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
trillium = { version = "0.2.20", optional = true }
tungstenite = { version = "0.24.0", optional = true }
typesense = { version = "0.1.0", optional = true }
unicode-segmentation = "1.12.0"
url = "2.5.3"
walkdir = "2.5.0"
wasmtime = "27.0.0"
watchmaker = { version = "2.0.0", optional = true }
watt = { version = "0.5.0", optional = true }
# wgpu = { version = "23.0.0", optional = true } # TODO P3 review prerequisites
windows = { version = "0.58.0", optional = true }
# xilem = { version = "0.1.0", optional = true } # TODO P3 review prerequisites
xshell = { version = "0.2.6", optional = true }
# xsv = "0.13.0" # not a lib
yapp = { version = "0.4.1", optional = true }
yew = { version = "0.21.0", optional = true }
# zed  # the `zed` crate is not the editor
zenoh = { version = "1.0.2", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
syslog = "7.0.0"

[build-dependencies]
cc = "1.2.1"
## we no longer use `skeptic` and friends below - see `build.rs` and the `package.build` setting above.
#anyhow = "1"
#build-info-build = "0.0.34"
## The git dependency will be used locally; when published to a registry like crates.io, it will use the registry version.
#mdbook-utils = { git = 'https://github.com/john-cd/mdbook-utils.git', version = "0.*" }
#skeptic = "0.13"
#walkdir = "2"

[dev-dependencies]
## Used for testing
rusty-fork = "0.3.0"
## We no longer use skeptic - see `build.rs` and the `package.build` setting above.
#skeptic = "0.13"

## `cargo-husky` handles git hook scripts
[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["user-hooks"]
## Note that, when user-hooks feature is enabled, other all features are disabled.
## You need to prepare all hooks in .cargo-husky/hooks directory.
## See https://lib.rs/crates/cargo-husky

[features]
## The `ci` feature should be turned "on" only during CI tests
## It is used to ignore certain tests that can't run there.
ci = []

## Dependencies that are CURRENTLY unused in the examples (marked as optional above)
## You may check for conflicts with: cargo build --features unused
unused = [
    "dep:accesskit",
    "dep:actix-web",
    "dep:axum",
    "dep:bevy",
    "dep:build-info",
    "dep:candle-core",
    "dep:cornucopia",
    "dep:cosmic-text",
    "dep:cross",
    "dep:crux_core",
    "dep:datafusion",
    "dep:diesel",
    "dep:duct",
    "dep:egui",
    "dep:elasticsearch",
    "dep:form_urlencoded",
    "dep:glidesort",
    "dep:globset",
    "dep:gping",
    "dep:hyper",
    "dep:iced",
    "dep:indicatif",
    "dep:infisearch",
    "dep:kani",
    "dep:leptos",
    "dep:linfa",
    "dep:loco",
    "dep:meilisearch",
    "dep:minisearch",
    "dep:mio",
    "dep:mongodb",
    "dep:monostate",
    "dep:nom",
    "dep:opencv",
    "dep:openrr",
    "dep:paste",
    "dep:pest",
    "dep:petgraph",
    "dep:plotly",
    "dep:polars",
    "dep:postscript",
    "dep:postage",
    "dep:proc-macro2",
    "dep:pyoxidizer",
    "dep:quote",
    "dep:r3bl_tuify",
    "dep:remove_dir_all",
    "dep:rhai",
    "dep:riker",
    "dep:rust_cache",
    "dep:RustQuant",
    "dep:salsa",
    "dep:sea-orm",
    "dep:seaography",
    "dep:sled",
    "dep:slint",
    "dep:slotmap",
    "dep:smol",
    "dep:stakker",
    "dep:starship",
    "dep:swc_ecma_parser",
    "dep:syn",
    "dep:tantivy",
    "dep:tauri",
    "dep:tinysearch",
    "dep:tonic",
    "dep:trillium",
    "dep:tungstenite",
    "dep:typesense",
    "dep:watchmaker",
    "dep:watt",
    "dep:windows",
    "dep:yapp",
    "dep:yew",
    "dep:zenoh",
]
