[package]
name = "rust_howto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
confy = "0.5.1"
crossbeam-channel = "0.5.9"
dashmap = "5.5.3"
derive_more = "0.99.17"
dotenvy = "0.15.7"
envy = "0.4.2"
futures = "0.3.29"
http = "1.0.0"
http-body-util = "0.1.0"
once_cell = "1.19.0"
parking_lot = "0.12.1"
rayon = "1.8.0"
reqwest = "0.11.22"
sea-orm = "0.12.9"
serde = { version = "1.0.193", features = ["derive"] }
serde_derive = "1.0.193"
tokio = { version = "1.35.0", features = ["full"] }
tower = "0.4.13"
tower-http = "0.5.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
