[package]
name = "deps" # All crate DEPendencies for the book's examples are stored below.
version = "0.1.0"
edition = "2021"
publish=false
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
approx = "0.5.1"
base64 = "0.21.7"
bitflags = "2.4.2"
byteorder = "1.5.0"
cc = "1.0.83"
chrono = "0.4.31"
anyhow = "1.0.79"
async-trait = "0.1.77"
bytes = "1.5.0"
clap = { version = "4.4.18", features = ["derive"] }
clap-verbosity-flag = "2.1.2"
concat-string = "1.0.1"
concat_strs = "1.0.2"
confy = "0.6.0"
crossbeam = "0.8.4"
crossbeam-channel = "0.5.11"
crossbeam-queue = "0.3.11"
crossbeam-utils = "0.8.19"
csv = "1.3.0"
data-encoding = "2.5.0"
dashmap = "5.5.3"
derive_more = "0.99.17"
doc-comment = "0.3.3"
dotenvy = "0.15.7"
env_logger = "0.11.0"
envy = "0.4.2"
flate2 = "1.0.28"
futures = "0.3.30"
glob = "0.3.1"
http = "1.0.0"
http-body-util = "0.1.0"
# image = "0.24.8"
lazy_static = "1.4.0"
log = "0.4.20"
log4rs = "1.2.0"
memmap = "0.7"
mime = "0.3.17"
miette = { version = "5.10.0", features = ["fancy"] }
nalgebra = { version = "0.32.3", features = ["serde-serialize"] }
ndarray = { version = "0.15.6", features = ["approx"] }
num = "0.4.1"
num_cpus = "1.16.0"
percent-encoding = "2.3.1"
petgraph = "0.6.4"
postgres = "0.19.7"
once_cell = "1.19.0"
# openssl = { version = "0.10.62", features = ["vendored"] }
parking_lot = "0.12.1"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.8.1"
regex = "1.10.2"
reqwest = { version = "0.11.23", features = ["blocking", "json", "stream"] }
ring = "0.17.7"
rusqlite = { version = "0.30.0", features = ["chrono"] }
same-file = "1.0.6"
select = "0.6.0"
sea-orm = "0.12.11"
semver = "1.0.21"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4.40"
tempfile = "3.9.0"
thiserror = "1.0.56"
threadpool = "1.8.1"
tokio = { version = "1.35.1", features = ["full"] }
tokio-graceful-shutdown = "0.14.2"
toml = "0.8.8"
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.1", features = ["full", "auth"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
unicode-segmentation = "1.10.1"
url = "2.5.0"
walkdir = "2.4.0"
#build-info = "0.0.34"

[target.'cfg(target_os = "linux")'.dependencies]
syslog = "6.1.0"

[build-dependencies]
skeptic = "0.13.7"
walkdir = "2.4.0"
anyhow = "1.0.79"
#build-info-build = "0.0.34"

[dev-dependencies]
skeptic = "0.13.7"
walkdir = "2.4.0"
anyhow = "1.0.79"
