[package]
name = "rust_howto"
version = "0.1.0"
edition = "2021"
publish=false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [[bin]]
# name = "sitemap"

[dependencies]
doc-comment = "0.3.3"
anyhow = "1.0.77"
async-trait = "0.1.75"
bytes = "1.5.0"
confy = "0.5.1"
crossbeam-channel = "0.5.9"
crossbeam-queue = "0.3.10"
crossbeam-utils = "0.8.18"
dashmap = "5.5.3"
derive_more = "0.99.17"
dotenvy = "0.15.7"
envy = "0.4.2"
futures = "0.3.29"
http = "1.0.0"
http-body-util = "0.1.0"
miette = { version = "5.10.0", features = ["fancy"] }
once_cell = "1.19.0"
parking_lot = "0.12.1"
rayon = "1.8.0"
reqwest = "0.11.22"
sea-orm = "0.12.9"
semver = "1.0.20"
serde = { version = "1.0.193", features = ["derive"] }
serde_derive = "1.0.193"
thiserror = "1.0.52"
tokio = { version = "1.35.0", features = ["full"] }
tokio-graceful-shutdown = "0.14.2"
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.0", features = ["full", "auth"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
walkdir = "2.4.0"
quick-xml = { version = "0.31.0", features = ["serialize"] }
