[package]
# All crate DEPendencies for the book's examples are stored below.
name = "deps"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license = "MIT OR Apache-2.0"
keywords.workspace = true
categories.workspace = true
workspace = ".."
build = false               # disable build.rs script detection; use: build = "build.rs" or build = "custom.rs" otherwise
#exclude.workspace = true
#include.workspace = true
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.91"
approx = "0.5.1"
async-trait = "0.1.83"
base64 = "0.22.1"
bitflags = "2.6.0"
byteorder = "1.5.0"
bytes = "1.8.0"
crates_io_api = "0.11.0"
cc = "1.1.31"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
# clap-verbosity-flag = "2.1"
concat-string = "1.0.1"
concat_strs = "1.0.2"
confy = "0.6.1"
crossbeam = "0.8.4"
crossbeam-channel = "0.5.13"
crossbeam-queue = "0.3.11"
crossbeam-utils = "0.8.20"
csv = "1.3.0"
dashmap = "6.1.0"
data-encoding = "2.6.0"
derive_more = { version = "1.0.0", features = ["full"] }
# doc-comment = "0.3"
dotenvy = "0.15.7"
env_logger = "0.11.5"
envy = "0.4.2"
flate2 = "1.0.34"
futures = "0.3.31"
glob = "0.3.1"
http = "1.1.0"
http-body-util = "0.1.2"
image = "0.25.4"
itertools = "0.13.0"
lazy_static = "1.5.0"
log = "0.4.22"
log4rs = "1.3.0"
lru = "0.12.5"
memmap = "0.7.0"
miette = { version = "7.2.0", features = ["fancy"] }
mime = "0.3.17"
multimap = "0.10.0"
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
ndarray = { version = "0.16.1", features = ["approx"] }
notify = "7.0.0"
num = "0.4.3"
num_cpus = "1.16.0"
once_cell = "1.20.2"
# openssl = { version = "0.10", features = ["vendored"] }
parking_lot = "0.12.3"
percent-encoding = "2.3.1"
# petgraph = "0.6"
postgres = "0.19.9"
pyo3 = "0.22.5"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.10.0"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking", "json", "stream"] }
ring = "0.17.8"
rusqlite = { version = "0.32.1", features = ["chrono"] }
same-file = "1.0.6"
# sea-orm = "0.12"
select = "0.6.0"
semver = "1.0.23"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tar = "0.4.42"
tempfile = "3.13.0"
thiserror = "1.0.65"
threadpool = "1.8.1"
tokio = { version = "1.41.0", features = ["full"] }
tokio-graceful-shutdown = "0.15.1"
toml = "0.8.19"
tower = { version = "0.5.1", features = ["util"] }
tower-http = { version = "0.6.1", features = ["full", "auth"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
unicode-segmentation = "1.12.0"
url = "2.5.2"
walkdir = "2.5.0"
dyn-clone = "1.0.17"
flagset = "0.4.6"
redis = "0.27.5"
lettre = "0.11.10"
# actix-web = "4.9.0"
# arrow = "53.2.0"
# async-channel = "2.3.1"
# async-std = "1.13.0"
# async-stream = "0.3.6"
# cosmic-text = "0.12.1"
# cross = "0.2.5"
# diesel = "2.2.4"
# digest = "0.10.7"
# dotenv = "0.15.0"
# duct = "0.13.7"
# egui = "0.29.1"
# elasticsearch = "8.15.0-alpha.1"
# embassy = "0.0.0"
# eyre = "0.6.12"
# floem = "0.1.1"
# form_urlencoded = "1.2.1"
# futures-executor = "0.3.31"
# glidesort = "0.1.2"
# gping = "1.17.3"
# hyper = "1.5.0"
# iced = "0.13.1"
# indicatif = "0.17.8"
# infisearch = "0.10.1"
# just = "1.36.0"
# kanal = "0.1.0-pre8"
# kani = "0.0.1"
# lens = "0.1.0"
# leptos = "0.7.0-gamma3"
# linfa = "0.7.0"
# monostate = "0.1.13"
# native-windows-gui = "1.0.13"
# nom = "7.1.3"
# open = "5.3.0"
# opencv = "0.93.3"
# openrr = "0.1.0"
# paste = "1.0.15"
# pest = "2.7.14"
# plotly = "0.10.0"
# polars = "0.44.1"
# postage = "0.5.0"
# proc-macro2 = "1.0.89"
# pyoxidizer = "0.24.0"
# quote = "1.0.37"
# r3bl_tuify = "0.2.0"
# ratatui = "0.29.0"
# rhai = "1.19.0"
# riker = "0.4.2"
# roogle = "1.0.0"
# ruff = "0.0.1"
# rui = "0.6.1"
# RustQuant = "0.2.12"
# salsa = "0.16.1"
# seaography = "1.1.0"
# sled = "0.34.7"
# slint = "1.8.0"
# slotmap = "1.0.7"
# smol = "2.0.2"
# sqlx = "0.8.2"
# stakker = "0.2.11"
# starship = "1.21.1"
# stork-search = "1.6.0"
# swc_ecma_parser = "3.0.0"
# syn = "2.0.85"
# tantivy = "0.22.0"
# tauri = "2.0.6"
# tempdir = "0.3.7"
# termbook = "1.4.2"
# tinysearch = "0.8.2"
# tonic = "0.12.3"
# trillium = "0.2.20"
# typesense = "0.1.0"
# wasmtime = "26.0.0"
# watchmaker = "2.0.0"
# watt = "0.5.0"
# wgpu = "23.0.0"
# windows = "0.58.0"
# xilem = "0.1.0"
# xshell = "0.2.6"
# xsv = "0.13.0"
# yapp = "0.4.1"
# yew = "0.21.0"
# zed = "0.1.0"
# zenoh = "1.0.0"
# build-info = "0.0.34"

[target.'cfg(target_os = "linux")'.dependencies]
syslog = "7.0.0"

[build-dependencies]
cc = "1.0"
## we no longer use `skeptic` - see `build.rs` and package.build setting above.
#anyhow = "1"
#build-info-build = "0.0.34"
## The git dependency will be used locally; when published to a registry like crates.io, it will use the registry version.
#mdbook-utils = { git = 'https://github.com/john-cd/mdbook-utils.git', version = "0.*" }
#skeptic = "0.13"
#walkdir = "2"

[dev-dependencies]
rusty-fork = "0.3.0"
## we no longer use skeptic - see `build.rs`
#skeptic = "0.13"

[features]
#full = []
