[package]
name = "development_tools_profiling"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - development_tools_profiling"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "development_tools_profiling" ]
publish.workspace = true

[dependencies]
criterion = "0.5.1"
dhat = "0.3.3"

## Config for `divan` example below:
[dev-dependencies]
divan = "0.1.17"

[[bench]]
name = "divan"
# When set to false, you are responsible for defining a main() function to run tests and benchmarks.
harness = false

## Config for dhat example below:
## Profiles for the non root package are ignored.
# [profile.release]
# debug = 1

[features]
dhat-heap = []    # if you are doing heap profiling
dhat-ad-hoc = []  # if you are doing ad hoc profiling
