[package]
name = "internationalization"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - internationalization"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "internationalization" ]
publish.workspace = true

[dependencies]
## Internationalization
## TODO P2
