[package]
license-file.workspace = true
name = "science_robotics"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - science_robotics"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["science::robotics"]
publish.workspace = true
autolib = false

[features]
default = []
openrr = ["dep:openrr"]
rosrust = ["dep:rosrust", "dep:rosrust_msg"]

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
bonsai-bt = "0.11.0"
clap = { version = "4.6.1", features = ["derive"] }
openrr = { version = "0.1.0", optional = true }
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
zenoh = "1.9.0"

[target.'cfg(not(target_os = "windows"))'.dependencies]
rosrust = { version = "0.9.12", optional = true }
rosrust_msg = { version = "0.1.8", optional = true }

[[example]]
name = "artificial_intelligence"
path = "examples/artificial_intelligence/main.rs"
test = true

[[example]]
name = "control_systems"
path = "examples/control_systems/main.rs"
test = true

[[example]]
name = "hardware_integration"
path = "examples/hardware_integration/main.rs"
test = true

[[example]]
name = "perception_and_sensors"
path = "examples/perception_and_sensors/main.rs"
test = true

[[example]]
name = "robot_operating_systems"
path = "examples/robot_operating_systems/main.rs"
test = true

[[example]]
name = "robotics_frameworks"
path = "examples/robotics_frameworks/main.rs"
test = true

[[example]]
name = "simulation_visualization"
path = "examples/simulation_visualization/main.rs"
test = true
