[package]
name = "science_robotics"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - science_robotics"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["science_robotics"]
publish.workspace = true
autolib = false

[dependencies]
bonsai-bt = "0.10.0"
# FIXME openrr = { version = "0.1.0", optional = true } # FIXME lacks native static library `assimpd` on windows https://github.com/assimp/assimp/blob/master/Build.md
# LATER add example? urdf-rs = "0.9.0"
# FIXME zenoh = { version = "1.1.0", optional = true } # https://github.com/john-cd/rust_howto/issues/1441

## General
anyhow = "1.0.95"
# tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"]  }
# tracing = "0.1.41"
# tracing-subscriber = "0.3.20"
# async-trait = "0.1.85"

# FIXME
#[features]
#default = []
#openrr = ["dep:openrr"]
#zenoh = ["dep:zenoh"]
