[package]
name = "science_robotics"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - science_robotics"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["science::robotics"]
publish.workspace = true
autolib = false

[dependencies]
bonsai-bt = "0.10.0"
openrr = "0.1.0"
rosrust = "0.9.12"
rosrust_msg = "0.1.8"
zenoh = "1.1.0" # https://github.com/john-cd/rust_howto/issues/1441

## General
anyhow = "1.0.95"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
async-trait = "0.1.85"

[features]
default = []
