[package]
name = "science_robotics"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - science_robotics"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["science::robotics"]
publish.workspace = true
autolib = false

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
bonsai-bt = "0.11.0"
openrr = { version = "0.1.0", optional = true }
zenoh = "1.9.0"
anyhow = "1.0.102"
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
async-trait = "0.1.89"

[target.'cfg(not(target_os = "windows"))'.dependencies]
rosrust = { version = "0.9.12", optional = true }
rosrust_msg = { version = "0.1.8", optional = true }

[features]
default = []
openrr = ["dep:openrr"]
rosrust = ["dep:rosrust", "dep:rosrust_msg"]
