[package]
name = "virtualization"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - virtualization"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["virtualization"]
publish.workspace = true
autolib = false

[dependencies]
wasmi = "1.0.9"

[[example]]
name = "virtualization"
path = "examples/virtualization/main.rs"
test = true
