[package]
name = "web_programming"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - web_programming"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "web_programming" ]
publish.workspace = true

[dependencies]
http = "1.1.0"
http-body-util = "0.1.2"
url.workspace = true
reqwest.workspace = true
select = "0.6.0"
mime = "0.3.17"

## General
anyhow.workspace = true
lazy_static.workspace = true
regex.workspace = true
tokio.workspace = true
