[package]
name = "os_unix_apis"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - os_unix_apis"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["os::unix-apis"]
publish.workspace = true
autolib = false

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }

[target.'cfg(target_family = "unix")'.dependencies]
nix = { version = "0.31.2", features = ["fs"] }
rustix = { version = "1.1.4", features = ["fs"] }

[[example]]
name = "unix"
path = "examples/unix/main.rs"
test = true
