[package]
name = "science_neuroscience"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - science_neuroscience"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = [ "science::neuroscience" ]
publish.workspace = true
autolib = false

[dependencies]
ndarray = "0.17"
nifti = { version = "0.17", features = ["ndarray_volumes"] }
