# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "/code/bk/crates/cats/database/tests/query_builders_orms/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/code/bk/crates/cats/database/tests/query_builders_orms/migrations"
