[package]
name = "wxyz"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## The dependencies that are NOT USED (YET) in examples are marked `optional = true`,
## in order to keep the compile speed decent.
## Remove the optional flag as needed.
[dependencies]

## WASM
wasmtime = { version = "28.0.0", optional = true }
yew = { version = "0.21.0", optional = true }

## Web
http = "1.1.0"
http-body-util = "0.1.2"
url = "2.5.3"
select = "0.6.0"

## Web - client
reqwest = { version = "0.12.9", features = ["blocking", "json", "stream"] }
hyper = { version = "1.5.0", optional = true }

## Web - server
actix-web = { version = "4.9.0", optional = true }
axum = { version = "0.7.7", optional = true }
mime = "0.3.17"
loco = { version = "0.13.2", optional = true }
tonic = { version = "0.12.3", optional = true }
tower = { version = "0.5.1", features = ["util"] }
tower-http = { version = "0.6.1", features = ["full", "auth"] }
trillium = { version = "0.2.20", optional = true }

## Websocket
tungstenite = { version = "0.26.0", optional = true }

anyhow = "1.0.91"
bytes = "1.9.0"
lazy_static = "1.5.0"
serde = { version = "1.0.216", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
regex = "1.11.1"

[features]

## Dependencies that are CURRENTLY unused in the examples (marked as optional above)
## You may check for conflicts with: cargo build --features unused or cargo build --all-features
unused = [
    "dep:actix-web",
    "dep:axum",
    "dep:hyper",
    "dep:loco",
    "dep:tonic",
    "dep:trillium",
    "dep:tungstenite",
    "dep:wasmtime",
    "dep:yew",
]
