[package]
name = "c"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## The dependencies that are NOT USED (YET) in examples are marked `optional = true`,
## in order to keep the compile speed decent.
## Remove the optional flag as needed.
[dependencies]

## Caching
lru = "0.12.5"

## Command-line interface
ansi_term = "0.12.1" # NOTE: unmaintained
clap = { version = "4.5.23", features = ["derive"] }
clap-verbosity-flag = { version = "3.0.0" , optional = true }
console = "0.15.10"
crossterm = "0.28.1"
indicatif = "0.17.9"
inquire = "0.7.5"
ratatui = "0.29.0" # requires crossterm

## Command-line utilities
starship = { version = "1.21.1", optional = true }

## Compilers
salsa = { version = "0.16.1", optional = true }

## Compression
flate2 = "1.0.35"
tar = "0.4.43"

## Computer vision
image = "0.25.5"
opencv = "0.93.3" # requires `libopencv-dev` `clang` `libclang-dev`

## Concurrency
crossbeam = "0.8.4"
crossbeam-channel = "0.5.14"
crossbeam-queue = "0.3.12"
crossbeam-utils = "0.8.21"
flume = {version = "0.11.1", features = ["select"] }
ractor = "0.14.2"
rayon = "1.10.0"
riker = { version = "0.4.2", optional = true }
stakker = { version = "0.2.11", optional = true }
threadpool = "1.8.1"

## Config
config = "0.15.3"
confy = "0.6.1"
# dotenv = "0.15.0" # outdated, replaced by dotenvy
dotenvy = "0.15.7"
envy = "0.4.2"

## Crypto
argon2 = "0.5.3"
bcrypt = "0.16.0"
curve25519-dalek = { version = "4.1.3", optional = true }
der = { version = "0.7.9", features = ["derive", "alloc"] }
ed25519-dalek = { version = "2.1.1", optional = true }
md5 = "0.7.0"
ring = "0.17.8"
scrypt = "0.11.0"
sha2 = "0.10.8"

anyhow = "1.0.94"
dashmap = "6.1.0"
data-encoding = "2.6.0"
glob = "0.3.1"
lazy_static = "1.5.0"
num = "0.4.3"
num_cpus = "1.16.0"
parking_lot = "0.12.3"
rand = "0.9.0-beta.1"
serde = { version = "1.0.216", features = ["derive"] }
walkdir = "2.5.0"
serde_derive = "1.0.216"
tokio = "1.42.0"
async-trait = "0.1.83"
lexopt = "0.3.0"

[features]

## Dependencies that are CURRENTLY unused in the examples (marked as optional above)
## You may check for conflicts with: cargo build --features unused or cargo build --all-features
unused = [
    "dep:clap-verbosity-flag",
    "dep:curve25519-dalek",
    "dep:ed25519-dalek",
    "dep:riker",
    "dep:salsa",
    "dep:stakker",
    "dep:starship",
]
