[package]
name = "c"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

## Caching
lru = "0.12.5"

## Command-line interface
ansi_term = "0.12.1" # NOTE: unmaintained
clap = { version = "4.5.23", features = ["derive"] }
clap-verbosity-flag = { version = "3.0.0" , optional = true } # TODO
console = "0.15.10"
crossterm = "0.28.1"
indicatif = "0.17.9"
inquire = "0.7.5"
pico-args = "0.5.0"
ratatui = "0.29.0" # requires crossterm

## Command-line utilities
starship = { version = "1.21.1", optional = true } # TODO

## Compilers
salsa = { version = "0.16.1", optional = true } # TODO

## Compression
flate2 = "1.0.35"
tar = "0.4.43"

## Concurrency
actix = "0.13.5"
await-tree = "0.2.1"
crossbeam = "0.8.4"
crossbeam-channel = "0.5.14"
crossbeam-queue = "0.3.12"
crossbeam-utils = "0.8.21"
flume = {version = "0.11.1", features = ["select"] }
futures = "0.3.31"
parking_lot = "0.12.3"
ractor = "0.14.2"
rayon = "1.10.0"
riker = { version = "0.4.2", optional = true } # TODO
stakker = "0.2.11"
threadpool = "1.8.1"

## Config
config = "0.15.3"
confy = "0.6.1"
# dotenv = "0.15.0" # outdated, replaced by dotenvy
dotenvy = "0.15.7"
envy = "0.4.2"
lexopt = "0.3.0"

## Crypto
aes-gcm-siv = "0.11.1"
aes-gcm = "0.10.3"
argon2 = "0.5.3"
bcrypt = "0.16.0"
curve25519-dalek = { version = "4.1.3", optional = true } # TODO
der = { version = "0.7.9", features = ["derive", "alloc"] }
dsa = "0.6.3"
ed25519-dalek = { version = "2.1.1", optional = true } # TODO
ecdsa = "0.16.9"
md5 = "0.7.0"
native-tls = "0.2.12"
p256 = "0.13.2"
pkcs8 = "0.10.2"
ring = "0.17.8"
rsa = "0.9.7"
rustls = "0.23.20"
scrypt = "0.11.0"
sha2 = "0.10.8"
subtle = "2.6.1"
tokio-rustls = "0.26.1"
zeroize = "1.8.1"

## General
anyhow = "1.0.94"
async-trait = "0.1.83"
crates-io = "0.40.6"
dashmap = "6.1.0"
data-encoding = "2.6.0"
glob = "0.3.1"
hyper = "1.5.2"
hyper-tls = "0.6.0"
image = "0.25.5"
itertools = "0.14.0"
lazy_static = "1.5.0"
num = "0.4.3"
num_cpus = "1.16.0"
rand = "0.9.0-beta.1" # use beta
serde = { version = "1.0.216", features = ["derive"] }
serde_derive = "1.0.216"
time = "0.3.37"
tokio = { version = "1.42.0", features = ["full"] }
walkdir = "2.5.0"

[target.'cfg(target_os = "linux")'.dependencies]
## Computer vision
image = "0.25.5"
opencv = { version = "0.93.5", features = [ "clang-runtime" ] }  # requires `libopencv-dev` `clang` `libclang-dev`
