[package]
name = "encoding"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - encoding"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "encoding" ]
publish.workspace = true
build = "build.rs"

[dependencies]

## Encoding
base64 = "0.22.1"
bincode = "1.3.3"
bytemuck = { version = "1.21.0", features = ["derive"] }
byteorder = "1.5.0"
capnp = "0.20.3"
ciborium = "0.2.2"
data-encoding = "2.6.0"
flatbuffers = "25.1.21"
form_urlencoded = "1.2.1"
monostate = "0.1.13"
percent-encoding = "2.3.1"
postcard = "1.1.1"
protobuf = "3.7.1"
prost = "0.13.4"
prost-types = "0.13.4"
rkyv = "0.8.10"
rmp-serde = "1.3.0"
serde_json.workspace = true
toml = "0.8.19"
zerocopy = { version = "0.8.14", features = ["derive"] }

## General
anyhow.workspace = true
csv = "1.3.1"
serde.workspace = true
url.workspace = true
heapless = "0.7.17" # pinned to 0.7.17 for postcard
serde_ignored = "0.1.10"

[build-dependencies]
capnpc = "0.20.1"
prost-build = "0.13.4"
