[package]
license-file.workspace = true
name = "hardware_support"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - hardware_support"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["hardware-support"]
publish.workspace = true
autolib = false

[dependencies]
num_cpus = "1.17.0"

[[example]]
name = "processor"
path = "examples/processor/main.rs"
test = true
