[package]
name = "email"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - email"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "email" ]
publish.workspace = true

[dependencies]
## Email
lettre = { version = "0.11.11", features = [ "tokio1-native-tls" ] }
