[package]
name = "parser_implementations"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - parser_implementations"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["parser-implementations"]
publish.workspace = true
autolib = false

[package.metadata.cargo-machete]
ignored = ["rust-ini"]

[features]
sqlparser = ["dep:sqlparser"]

[dependencies]
anyhow = "1.0.102"
basic-toml = "0.1.10"
chrono = { version = "0.4.44", features = ["serde"] }
clap = { version = "4.6.1", features = ["derive"] }
comrak = "0.52.0"
cssparser = "0.37.0"
html5ever = "0.39.0"
json5 = "1.3.1"
markdown = "1.0.0"
markup5ever = "0.39.0"
markup5ever_arcdom = "0.1.2"
pulldown-cmark = "0.13.3"
quick-xml = { version = "0.39.2", features = ["serialize"] }
roxmltree = "0.21.1"
rust-ini = "0.21.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yml = "0.0.12"
simd-json = "0.17.0"
sqlparser = { version = "0.61.0", features = ["visitor"], optional = true }
swc_common = "21.0.1"
swc_ecma_ast = "23.0.0"
swc_ecma_parser = "39.0.2"
tl = "0.7.8"
toml = "1.1.2"
toml_edit = "0.25.11"
xml = "1.2.1"
xml5ever = "0.39.0"
xmlparser = "0.13.6"
