[package]
name = "other"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
autolib = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# FIXME
[dependencies]

## Architecture
shaku = "0.6.2"

## Cloud
aws-config = "1.6.2"
aws-sdk-s3 = "1.68.0"
# FIXME lambda_runtime = "0.14.2"
# FIXME shuttle-runtime = "0.56.0"

## Cross platform
crux_core = "0.16.0"
# FIXME do we need? crux_macros = "0.6.1"

## Data processing
arrow = { version = "56.1.0", features = ["prettyprint"], optional = true }
# FIXME datafusion = { version = "47.0.0", optional = true } # Heavy compile
# FIXME polars = { version = "0.49.1", optional = true } # Heavy compile

## GPU
# FIXME

## Scripting
rhai = "1.21.0"

## General
anyhow = "1.0.95"
async-trait = "0.1.85"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[features]
datafusion = [] # FIXME "dep:datafusion"
polars = [] # FIXME "dep:polars"
arrow = ["dep:arrow"]
## For Crux:
typegen = ["crux_core/typegen"]
