[package]
name = "command_line_interface"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - command_line_interface"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["command-line-interface"]
publish.workspace = true
autolib = false

[dependencies]
ansi_term = "0.12.1" # NOTE: unmaintained

## General
anyhow = "1.0.100"
clap = { version = "4.5.50", features = ["derive"] }
clap_complete = "4.5.46"
colored = "3.0.0"
console = "0.16.1"
crossterm = "0.29.0"
indicatif = "0.18.1"
inquire = "0.9.1"
lexopt = "0.3.1"
pico-args = "0.5.0"
ratatui = "0.29.0"                                   # requires crossterm
