[package]
name = "command_line_interface"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - command_line_interface"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["command_line_interface"]
publish.workspace = true
autolib = false

[dependencies]
ansi_term = "0.12.1"                                 # NOTE: unmaintained
clap = { version = "4.5.31", features = ["derive"] }
# clap_complete = "4.5.46"
# FIXME clap-verbosity-flag = "3.0.0"
console = "0.16.0"
crossterm = "0.29.0"
indicatif = "0.17.9"
inquire = "0.7.5"
lexopt = "0.3.1"
pico-args = "0.5.0"
ratatui = "0.29.0"   # requires crossterm

## General
anyhow = "1.0.95"
# FIXME
# colored = "3.0.0"
