[package]
name = "compression"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - compression"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["compression"]
publish.workspace = true

[dependencies]
flate2 = "1.0.35"
tar = "0.4.43"

## General
anyhow.workspace = true
