[package]
name = "compilers"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Examples focused on compiler design and incremental computation using Salsa and Comemo."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["compilers", "incremental", "salsa", "comemo", "ast"]
categories = ["compilers"]
publish.workspace = true
autolib = false

[dependencies]
comemo = "0.5.0"
salsa = "0.26.0"

## General
anyhow = "1.0.95"
