[package]
name = "compilers"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Examples focused on compiler design and incremental computation using Salsa and Comemo."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["compilers", "incremental", "salsa", "comemo", "ast"]
categories = ["compilers"]
publish.workspace = true
autolib = false

[dependencies]

## General
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
comemo = "0.5.1"
salsa = "0.26.1"

[[example]]
name = "incremental_computation"
path = "examples/incremental_computation/main.rs"
test = true

