[package]
name = "development_tools_build_utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - development_tools_build_utils"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["development-tools::build-utils"]
publish.workspace = true
build = "build.rs"
autolib = false

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
anyhow = "1.0.100"
autocfg = "1.5.0"
cc = "1.2.59"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

## See build.rs
[build-dependencies]
cc = "1.2.59"
