[package]
name = "other"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
autolib = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# FIXME
[dependencies]

## Architecture
shaku = "0.6.2"

## Cloud
aws-config = "1.6.2"
aws-sdk-s3 = "1.68.0"
# lambda_runtime = "0.14.2"

## Cross platform
crux_core = "0.15.0"
# crux_macros = "0.6.1"

## Data processing
arrow = { version = "55.0.0", features = ["prettyprint"], optional = true }
# datafusion = { version = "47.0.0", optional = true }
# polars = { version = "0.49.1", optional = true }

## GPU

## Scripting
rhai = "1.21.0"

## General
anyhow = "1.0.95"
async-trait = "0.1.85"
serde = { version = "1.0.217", features = ["derive"] }
tokio = "1.44.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

# FIXME
[features]
#datafusion = ["dep:datafusion"]
#polars = ["dep:polars"]
arrow = ["dep:arrow"]
## For Crux:
typegen = ["crux_core/typegen"]

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.29", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.29", features = ["build"] }
