[package]
name = "other"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
autolib = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

## Architecture
shaku = "0.6.2"

## Cloud
aws-config = "1.5.13"
aws-sdk-s3 = "1.68.0"
lambda_runtime = "0.13.0"

## Cross platform
crux_core = "0.12.0"
crux_macros = "0.4.4"

## Data processing
arrow = { version = "54.2.1", features = ["prettyprint"], optional = true }
datafusion = { version = "46.0.0", optional = true }
#polars = { version = "0.46.0", optional = true } # FIXME

## GPU
# FIXME add deps

## Scripting
rhai = "1.21.0"

## Written in Rust FIXME
# bat
# broot
# exa = "0.10.1" # FIXME review conflicts
# gping = "1.17.3" # not a lib
# just = "1.36.0"
# lsd
# roogle # not a lib
# ruff # not a lib
# rui = "0.6.1" # experimental at this point
# rustdesk = "0.1.1" # app
# xsv = "0.13.0" # not a lib
# zed  # the `zed` crate is not the editor

## General
anyhow = "1.0.95"
async-trait = "0.1.87"
serde = { version = "1.0.217", features = ["derive"] }
tokio = "1.44.2"

[features]
#default = []
datafusion = ["dep:datafusion"]
#polars = ["dep:polars"]
arrow = ["dep:arrow"]
## For Crux:
typegen = ["crux_core/typegen"]

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.29", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.29", features = ["build"] }
