[package]
name = "game_engines"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - game_engines"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["game_engines"]
publish.workspace = true
autolib = false

[dependencies]
bevy = { version = "0.15.1", optional = true }
fyrox = "0.36.0"
fyrox-core = "0.36.0"
# ggez = "0.9.3"
# [ggez conflict with wgpu LATER](https://github.com/john-cd/rust_howto/issues/1289)
glam = "0.30.0"
macroquad = "0.4.13"

[features]
default = []
bevy = ["dep:bevy"]
#fyrox = ["dep:fyrox", "dep:fyrox-core"]
#ggez = ["dep:ggez"]
#macroquad = ["dep:macroquad"]
