[package]
license-file.workspace = true
name = "asynchronous"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples for Asynchronous programming with Tokio, Smol, and Rayon."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["async", "tokio", "smol", "futures", "concurrency"]
categories = ["asynchronous"]
publish.workspace = true
autolib = false

[dependencies]

## General
anyhow = "1.0.102"
async-channel = "2.5.0"
# LATER async-stream = "0.3.6"
async-trait = "0.1.89"
clap = { version = "4.6.1", features = ["derive"] }
futures = "0.3.32"
futures-executor = "0.3.32"
futures-util = "0.3.32"
kanal = "0.1.1"                                                        # NOTE: pre version
mio = "1.2.0"
postage = "0.5.0"
rand = { version = "0.10.1", features = ["thread_rng"] }
rayon = "1.12.0"
reqwest = "0.13.3"
smol = "2.0.2"
time = "0.3.47"
tokio = { version = "1.52.1", features = ["rt-multi-thread", "fs"] }
tokio-graceful-shutdown = "0.19.3"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[[example]]
name = "async"
path = "examples/async/main.rs"
test = true

[[example]]
name = "async_channels"
path = "examples/async_channels/main.rs"
test = true

[[example]]
name = "async_traits"
path = "examples/async_traits/main.rs"
test = true

[[example]]
name = "call_async_from_blocking"
path = "examples/call_async_from_blocking/main.rs"
test = true

[[example]]
name = "call_blocking_from_async"
path = "examples/call_blocking_from_async/main.rs"
test = true

[[example]]
name = "futures"
path = "examples/futures/main.rs"
test = true

[[example]]
name = "mio"
path = "examples/mio.rs"
test = true

[[example]]
name = "smol"
path = "examples/smol.rs"
test = true

[[example]]
name = "streams"
path = "examples/streams/main.rs"
test = true

[[example]]
name = "tokio"
path = "examples/tokio/main.rs"
test = true
