[package]
name = "parsing"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - parsing"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "parsing" ]
publish.workspace = true

[dependencies]
## Parsing and friends
nom = "8.0.0"
pest = "2.7.15"
pest_derive = "2.7.15"
tree-sitter = "0.25.1"
tree-sitter-rust = "0.23.2"

[build-dependencies]
pest_generator = "2.7.15"
cc = "1.2"
