[package]
name = "cargo"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
xshell = "0.2.7"

## General
anyhow = "1.0.97"
tempfile = "3.19.1"
