[package]
name = "cargo"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["development-tools::cargo-plugins"]
publish.workspace = true

[dependencies]

## General
anyhow = "1.0.100"
tempfile = "3.23.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
xshell = "0.2.7"
