publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# General
anyhow.workspace = true
approx.workspace = true
serde_json.workspace = true
hyper = "1.5.2"
tokio.workspace = true
