[package]
license-file.workspace = true
name = "development_tools_testing"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Examples of advanced testing techniques including property-based testing, mocking, and fuzzing."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["testing", "proptest", "mockall", "insta", "fuzzing", "bolero"]
categories = ["development-tools::testing"]
publish.workspace = true
autolib = false

[dependencies]
afl = "0.18.1"
approx = "0.5.1" # was pinned at 0.4.0
arbitrary = { version = "1.4.2", features = ["derive"] }
bolero = "0.13.4"
clap = { version = "4.6.1", features = ["derive"] }
fake = { version = "5.1.0", features = ["derive"] }
faux = "0.1.13"
insta = "1.47.2"
mockall = "0.14.0"
proptest = "1.11.0"

## General

[[example]]
name = "assertions"
path = "examples/assertions/main.rs"
test = true

[[example]]
name = "code_coverage"
path = "examples/code_coverage/main.rs"
test = true

[[example]]
name = "fuzzing"
path = "examples/fuzzing/main.rs"
test = true

[[example]]
name = "mocking"
path = "examples/mocking/main.rs"
test = true

[[example]]
name = "property_based_testing"
path = "examples/property_based_testing/main.rs"
test = true

[[example]]
name = "test_runners"
path = "examples/test_runners/main.rs"
test = true

[[example]]
name = "testing"
path = "examples/testing/main.rs"
test = true
