[book]
authors = []
language = "en"
multilingual = false
src = "src"

[preprocessor.scrub]
command = "./target/debug/mdbook-scrub"

## The order in which preprocessors are run can be controlled with the before and after fields.
## See https://rust-lang.github.io/mdBook/format/configuration/preprocessors.html
before = [
    "links",
] # "links" expands the {{ #playground }}, {{ #include }}, and {{ #rustdoc_include }} handlebars helpers in a chapter to include the contents of a file.
#before = []

# Output as markdown (in addition to HTML) for debugging purposes
[output.markdown]
