[package]
name = "compilers"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish.workspace = true
autolib = false

[dependencies]
comemo = "0.4.0"
cross = "0.2.5"
salsa = "0.23.0"

## General
anyhow = "1.0.95"
