[package]
name = "multimedia_images"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - multimedia_images"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "multimedia_images" ]
publish.workspace = true

[dependencies]
# TODO P2
