[package]
name = "memory_management"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - memory_management"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "memory_management" ]
publish.workspace = true

[dependencies]
lazy_static.workspace = true
once_cell.workspace = true

# General
anyhow.workspace = true
