[package]
name = "command_line_interface"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - command_line_interface"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "command_line_interface" ]
publish.workspace = true

[dependencies]
## Command-line interface
ansi_term = "0.12.1" # NOTE: unmaintained
clap = { version = "4.5.23", features = ["derive"] }
# clap-verbosity-flag = "3.0.0" # TODO P2
console = "0.15.10"
crossterm = "0.28.1"
indicatif = "0.17.9"
inquire = "0.7.5"
pico-args = "0.5.0"
ratatui = "0.29.0" # requires crossterm

## General
anyhow.workspace = true
