[package]
name = "computer_vision"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - computer_vision"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["computer_vision"]
publish.workspace = true

[dependencies]
rand = { version = "0.9.0", features = ["thread_rng"] }

[target.'cfg(target_os = "linux")'.dependencies]
image = { version = "0.25.5", optional = true }
opencv = { version = "0.94.1", features = [
    "clang-runtime",
], optional = true } # requires `libopencv-dev` `clang` `libclang-dev`

[features]
# default = []
opencv = ["dep:opencv", "dep:image"]
