[package]
name = "web_programming_http_client"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - web_programming_http_client"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "web_programming_http_client" ]
publish.workspace = true

[dependencies]
## Web - client
hyper = "1.5.0"
hyper-util = "0.1.10"
reqwest = { workspace = true, features = ["blocking", "json", "stream"] }
ureq = "2.12.1"

## General
anyhow.workspace = true
#bytes = "1.9.0"
#futures-util = "0.3.31"
#lazy_static.workspace = true
#regex.workspace = true
serde.workspace = true
#serde_json.workspace = true
tokio.workspace = true
url.workspace = true
