[package]
name = "science_robotics"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - science_robotics"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["science_robotics"]
publish.workspace = true
autolib = false

[dependencies]
bonsai-bt = "0.10.0"
# openrr = "0.1.0" # FIXME lacks native static library `assimpd` on windows https://github.com/assimp/assimp/blob/master/Build.md
urdf-rs = "0.9.0"
# TODO zenoh = { version = "1.1.0", optional = true }

## General
anyhow = "1.0.97"
tokio = { version = "1.44.2", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
async-trait = "0.1.88"

[features]
#default = []
#openrr = ["dep:openrr"]
