[package]
name = "science_robotics"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - science_robotics"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["science_robotics"]
publish.workspace = true
autolib = false

[dependencies]
bonsai-bt = "0.10.0"
# openrr = "0.1.0" # FIXME P1 lacks native static library `assimpd` on windows https://github.com/assimp/assimp/blob/master/Build.md
urdf-rs = "0.9.0"
zenoh = { version = "1.1.0", optional = true }

[features]
#default = []
#openrr = ["dep:openrr"]
zenoh = ["dep:zenoh"]
