[package]
name = "c"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## The dependencies that are NOT USED (YET) in examples are marked `optional = true`,
## in order to keep the compile speed decent.
## Remove the optional flag as needed.
[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
clap-verbosity-flag = "3.0.0"
config = "0.15.3"
confy = "0.6.1"
console = "0.15.10"
crossbeam = "0.8.4"
crossbeam-channel = "0.5.14"
crossbeam-queue = "0.3.12"
crossbeam-utils = "0.8.21"
dashmap = "6.1.0"
data-encoding = "2.6.0"
dotenvy = "0.15.7"
envy = "0.4.2"
flate2 = "1.0.35"
glob = "0.3.1"
image = "0.25.5"
indicatif = "0.17.9"
lazy_static = "1.5.0"
lru = "0.12.5"
num = "0.4.3"
num_cpus = "1.16.0"
parking_lot = "0.12.3"
rand = "0.8.5"
rayon = "1.10.0"
ring = "0.17.8"
serde = "1.0.216"
tar = "0.4.43"
threadpool = "1.8.1"
walkdir = "2.5.0"
