[package]
name = "gui"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - gui"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "gui" ]
publish.workspace = true

[dependencies]

## GUI
arboard = "3.4.1"
cosmic-text = "0.12.1"
dioxus = "0.6.1"
dioxus-web = "0.6.1"
dioxus-desktop = "0.6.1"
eframe = "0.30.0"
egui = "0.30.0"
femtovg = "0.12.0"
# floem = "0.1.1" # FIXME P3 review requirements
# gtk = { version = "0.9.5", package = "gtk4" } # FIXME Make sure to use gtk4; for relm4 / gtk4 examples
iced = "0.13.1"
minifb = "0.28.0"
morphorm = "0.6.5"
pollster = "0.4" # for vello example
r3bl_tuify = "0.2.0"
# relm4 = "0.9.1"
# relm4-components = "0.9.1"
# # FIXME P1 https://gtk-rs.org/gtk4-rs/git/book/installation_linux.html
# # FIXME P1 https://gtk-rs.org/gtk4-rs/git/book/installation_windows.html
rfd = "0.15.2"
skia-safe = { version = "0.78", features = ["gl"] } # pin to 0.78 for slint
slint = "1.9.1"
taffy = "0.7.5"
tao = "0.31.1"
tauri = "2.0.6"      # Requires multiple libraries. See Dockerfile
vello = "0.4.0"
vger = "0.4.0"
# vizia = "0.2.0" # FIXME P1 conflict with skia-safe
# webrender = "0.61.0" # FIXME P2 conflicts with RustQuant - native library `freetype`
winit = "0.30.8" # for vello, winit examples
xilem = "0.1.0"
anyhow.workspace = true
