[package]
name = "virtualization"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - virtualization"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "virtualization" ]
publish.workspace = true
autolib = false

[dependencies]
# [review  wasmi](https://github.com/john-cd/rust_howto/issues/1263)
