[package]
name = "rendering_data_formats"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - rendering_data_formats"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "rendering_data_formats" ]
publish.workspace = true

[dependencies]
