[package]
name = "template_engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Code examples for popular Rust template engines including Tera and TinyTemplate."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["templates", "tera", "tinytemplate", "web", "rendering"]
categories = ["template-engine"]
publish.workspace = true
autolib = false

[dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
tera = "1.20.0"
tinytemplate = "1.2.1"
