[package]
name = "wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - wasm"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["wasm"]
publish.workspace = true
autolib = false

[features]
wasmtime = ["dep:wasmtime"]

[dependencies]

## General
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
# LATER add example?
js-sys = "0.3.97"
wasm-bindgen = "0.2.120"
wasmer = "6.1.0"
wasmtime = { version = "41.0.4", optional = true } # Heavy compile
web-sys = { version = "0.3.97", features = ["Window"] }
yew = { version = "0.23.0", features = ["csr"] }
