[package]
name = "wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - wasm"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "wasm" ]
publish.workspace = true

[dependencies]
## WASM
wasmer = "5.0.4"
wasmtime = "28.0.0"
yew = { version = "0.21.0", features = [ "csr" ] }

## General
anyhow.workspace = true
#bytes = "1.9.0"
#futures-util = "0.3.31"
#lazy_static.workspace = true
#regex.workspace = true
#serde.workspace = true
#serde_json.workspace = true
#tokio.workspace = true
