[package]
name = "api_bindings"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - api_bindings"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["api_bindings"]
publish.workspace = true
autolib = false

[dependencies]

[target.'cfg(target_os = "linux")'.dependencies]
pyo3 = "0.24.0" # was pinned to 0.21 to avoid conflict with `polars`

[features]
# default = []
# pyo3 = ["dep:pyo3"]
