[package]
name = "ab"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - categories A and B"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

## Accessibility
accesskit = "0.17.1"

## Aerospace and friends

## Algorithms
# glidesort = "0.1.2" # TODO
rand.workspace = true
rand_distr = "0.4.3"

## API bindings
## See below

## Async
async-channel = "2.3.1"
# async-std = "1.13.0"
# async-stream = "0.3.6"
async-trait.workspace = true
duct = "0.13.7"
futures = "0.3.31"
futures-executor = "0.3.31"
kanal = "0.1.0-pre8" # NOTE: pre version
mio = "1.0.2"
parking_lot = "0.12.3"
postage = "0.5.0"
rayon = "1.10.0"
reqwest.workspace = true
smol = "2.0.2"
tempfile = "3.14.0"
tokio.workspace = true
tokio-graceful-shutdown = "0.15.2"

## Authentication

## General
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
pyo3 = "0.21" # was pinned to 0.21 to avoid conflict with `polars`
