[package]
name = "ab"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## The dependencies that are NOT USED (YET) in examples are marked `optional = true`,
## in order to keep the compile speed decent.
## Remove the optional flag as needed.
[dependencies]

## Accessibility
accesskit = { version = "0.17.0", optional = true }

## Aerospace and friends

## Algorithms
glidesort = { version = "0.1.2", optional = true }
rand = "0.8.5"
rand_distr = "0.4.3"

## API bindings
## See below

## Async
async-channel = "2.3.1"
async-std = { version = "1.13.0", optional = true }
async-stream = { version = "0.3.6" , optional = true }
async-trait = "0.1.83"
duct = { version = "0.13.7", optional = true }
futures = "0.3.31"
futures-executor = { version = "0.3.31", optional = true }
kanal = "0.1.0-pre8" # NOTE: pre version
mio = { version = "1.0.2", optional = true }
parking_lot = { version = "0.12.3", optional = true }
postage = "0.5.0"
rayon = "1.10.0"
reqwest = "0.12.9"
smol = { version = "2.0.2", optional = true }
tempfile = "3.14.0"
tokio = { version = "1.42.0", features = ["full"] }
tokio-graceful-shutdown = "0.15.2"

## Authentication

anyhow = "1.0.94"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[target.'cfg(target_os = "linux")'.dependencies]
# TODO P1 proper version number
pyo3 = "*" # was pinned to 0.21 to avoid conflict with `polars`

[features]

## Dependencies that are CURRENTLY unused in the examples (marked as optional above)
## You may check for conflicts with: cargo build --features unused or cargo build --all-features
unused = [
    "dep:async-std",
    "dep:async-stream",
    "dep:accesskit",
    "dep:duct",
    "dep:futures-executor",
    "dep:glidesort",
    # "dep:kanal",
    "dep:mio",
    "dep:parking_lot",
    "dep:smol",
]
