[package]
name = "aerospace"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - aerospace"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["aerospace"]
publish.workspace = true
autolib = false

[dependencies]
sgp4 = "2.4.0"

## General
#anyhow = "1.0.95"

[[example]]
name = "aerospace"
path = "examples/aerospace/main.rs"
test = true
