[package]
name = "development_tools"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - development_tools"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "development_tools" ]
publish.workspace = true

[dependencies]
## Dev Tools
# TODO bacon ="3.2.0"
crates_io_api = "0.11.0"
cross = "0.2.5"
doc-comment = "0.3.3"
kani = "0.0.1"
# TODO
# mdbook
# mdbook-cmdrun
# mdbook-journal
# mdbook-keeper
# mdbook-linkcheck
# mdbook-pagetoc
# mdbook-private
# mdbook-tera
# mdbook-theme
# mdbook-toc
# miri
semver = "1.0.24"
# termbook = "1.4.2" # requires mdbook; TODO P3 review pre-requisites
yapp = "0.4.1"

## General
anyhow.workspace = true
#axum = "0.8.1"
#dotenvy = "0.15.7"
#serde.workspace = true
#serde_json.workspace = true
#tokio.workspace = true
tracing.workspace = true
