[package]
name = "accessibility"
edition = "2024"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
readme = "README.md"

[dependencies]
accesskit = "0.17.1"
accesskit_winit = "0.23.1"
winit = "0.30.8"
