[package]
name = "aerospace_protocols"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - aerospace_protocols"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["aerospace::protocols"]
publish.workspace = true
autolib = false

[dependencies]
mavlink = "0.17.1"

[[example]]
name = "aerospace_protocols"
path = "examples/aerospace_protocols/main.rs"
test = true

