[package]
license-file.workspace = true
name = "email"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - email"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["email"]
publish.workspace = true
autolib = false

[dependencies]
anyhow = "1.0.102"
lettre = { version = "0.11.21", features = ["tokio1-native-tls"] }

[[example]]
name = "lettre"
path = "examples/lettre.rs"
test = true
