[package]
license-file.workspace = true
name = "api_bindings"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - api_bindings"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["api-bindings"]
publish.workspace = true

[dependencies]

[[example]]
name = "api_bindings"
path = "examples/api_bindings/main.rs"
test = true
