[package]
name = "algorithms"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - algorithms"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["algorithms"]
publish.workspace = true
autolib = false

[dependencies]

## General
anyhow = "1.0.100"
base16ct = { version = "0.3.0", features = ["alloc"] }
base64ct = { version = "1.8.0", features = ["alloc"] }
blake3 = "1.8.2"
data-encoding = "2.9.0"
fastrand = "2.3.0"
hex-literal = "1.0.0"
md5 = "0.8.0"

petgraph = "0.8.3"
rand = "0.10.1"
rand_distr = "0.5.1"
ring = "0.17.14"
sha1 = "0.10.6"
sha2 = "0.10.9"
tempfile = "3.23.0"
