[package]
name = "parser_implementations"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - parser_implementations"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "parser_implementations" ]
publish.workspace = true

[dependencies]
# postscript = "0.18.2" # TODO P2
swc_ecma_parser = "6.0.1"
swc_ecma_ast = "5.0.1"
swc_common = "5.0.0"
