[package]
name = "parser_implementations"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - parser_implementations"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["parser_implementations"]
publish.workspace = true

[dependencies]
swc_ecma_parser = "7.0.0"
swc_ecma_ast = "5.0.1"
swc_common = "5.0.0"
