[package]
name = "aerospace_unmanned_aerial_vehicles"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - aerospace_unmanned_aerial_vehicles"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["aerospace::unmanned-aerial-vehicles"]
publish.workspace = true
autolib = false

[dependencies]
tello = "0.6.3"
