name: rust_howto_ci
services:
  book:
    image: rust_howto_ci:${IMAGE_VERSION}  # Name and tag of the image that will be built
    build:
      target: ci
      cache_from:
        - type=gha                          # GitHub Action cache
        #- type=local,dest=./.cache
        - johncd/rust_howto_ci:latest
      cache_to:
        - type=gha,mode=max
        #- type=local,dest=./.cache
    volumes:
      - type: bind
        source: ${BOOK_PATH}                # See .env file
        target: /code/book
