# Services for tests that require a database or external cache or search engines
# Don't try to run everything at once!
#
# Sources:
# https://github.com/docker/awesome-compose
# https://awesome-docker-compose.com
#
services:

  amqp:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  cassandra:
    image: cassandra
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_infra

  elasticsearch:
    image: elasticsearch:7.16.1
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:9200/_cluster/health || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 3

  meilisearch:
    image: getmeili/meilisearch:v1.12.0
    ports:
      - 7700:7700
    volumes:
      - ./meili_data:/meili_data
    restart: unless-stopped

  # https://hub.docker.com/_/mongo
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mysecretpassword

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    ports:
        - 1433:1433
    environment:
        SA_PASSWORD: "password123!"
        ACCEPT_EULA: "Y"

  oracle:
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
    ports:
      - 1521:1521

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=library
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432

  # https://hub.docker.com/_/redis
  redis:
    image: redis:alpine
    restart: always
    # command: redis-server --requirepass yourpassword # or edit redis.conf
    expose:
      - 6379

volumes:
  db_data: {}
