services:
  book:
    image: rust_howto_ci:${IMAGE_VERSION}  # Name and tag of the image that will be built
    volumes:
      - type: bind
        source: ./book       # on Windows, something like: /d/book
        target: /code/book
