services:
  book:
    image: rust_howto_ci:${IMAGE_VERSION}  # Name and tag of the image that will be built
    volumes:
      - type: bind
        source: ${BOOK_PATH}       # on Windows, something like: /d/book; on Linux, ../book; relative path is resolved from the Compose file’s directory
        target: /code/book
