# Docker Compose reference guide: https://docs.docker.com/go/compose-spec-reference/
version: "3.8"
services:
  book:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile  # path relative to context
      args:
        RUST_IMAGE_LABEL: ${RUST_IMAGE_LABEL}
        MDBOOK_VERSION: ${MDBOOK_VERSION}
      cache_from:
        - rust:${RUST_IMAGE_LABEL}
