# Docker Compose reference guide: https://docs.docker.com/go/compose-spec-reference/
services:
  book:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile # path relative to context
      args:
        RUST_IMAGE_LABEL: ${RUST_IMAGE_LABEL:?rust image label must be defined}
        MDBOOK_VERSION: ${MDBOOK_VERSION:?mdbook version must be defined}
