[package]
name = "science"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Scientific computing and machine learning examples using Ndarray, Linfa, and Candle."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["science", "machine-learning", "ndarray", "linfa", "candle", "ai"]
categories = ["science"]
publish.workspace = true
autolib = false

[features]
default = []
candle = ["dep:candle-core", "dep:candle-nn"]

[dependencies]
candle-core = { version = "0.10.2", optional = true }
candle-nn = { version = "0.10.2", optional = true }
clap = { version = "4.6.1", features = ["derive"] }
linfa = "0.8.1"
linfa-linear = "0.8.1"
ndarray = "0.16.1" # TODO upgrade to 0.17.2+
rand = { version = "0.10.1", features = ["std"] }
smartcore = "0.5.0"

[[example]]
name = "ml"
path = "examples/ml/main.rs"
test = true
