[package]
name = "opqr"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

## OS and friends
# See below
libc = "0.2.169"

## Parsing and friends
nom = "7.1.3"
pest = "2.7.15"
pest_derive = "2.7.15"
# postscript = "0.18.2" # TODO
swc_ecma_parser = "6.0.1"
swc_ecma_ast = "5.0.1"
swc_common = "5.0.0"
tree-sitter = "0.24.7"
tree-sitter-rust = "0.23.2"

## Rendering and friends

## Rust patterns
color-eyre = "0.6.3"
dyn-clone = "1.0.17"
# eyre = "0.6.12" # outdated, see color-eyre
itertools = "0.14.0"
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "2.0.1"

## General
anyhow.workspace = true
regex.workspace = true
reqwest = { workspace = true, features = ["blocking"] }

[target.'cfg(target_family = "unix")'.dependencies]
nix = { version = "0.29.0", features = ["fs"] }
rustix = "0.38.42"

[target.'cfg(target_os = "windows")'.dependencies]
# native-windows-gui = "1.0.13"   # TODO P3 review pre-requisites
# native-windows-derive = "1.0.3" # Required only if the derive macro is used.
winapi = { version = "0.3.9", features = ["winuser"] }
windows = { version = "0.59.0" }

[build-dependencies]
pest_generator = "2.7.15"
cc = "1.2"
