[package]
name = "opqr"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## The dependencies that are NOT USED (YET) in examples are marked `optional = true`,
## in order to keep the compile speed decent.
## Remove the optional flag as needed.
[dependencies]

## OS and friends
# See below
libc = "0.2.169"

## Parsing and friends
nom = "7.1.3"
pest = "2.7.15"
pest_derive = "2.7.15"
postscript = { version = "0.18.2", optional = true } # TODO
swc_ecma_parser = "6.0.1"
swc_ecma_ast = "5.0.1"
swc_common = "5.0.0"

## Rendering and friends

## Rust patterns
dyn-clone = "1.0.17"
# eyre = "0.6.12" # outdated, see color-eyre
itertools = "0.14.0"
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "2.0.1"

## General
anyhow = "1.0.94"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["blocking"] }

[target.'cfg(target_family = "unix")'.dependencies]
nix = { version = "0.29.0", features = ["fs"] }
rustix = "0.38.42"

[target.'cfg(target_os = "windows")'.dependencies]
# native-windows-gui = { version = "1.0.13", optional = true }   # TODO P3 review pre-requisites
# native-windows-derive = { version = "1.0.3", optional = true } # Required only if the derive macro is used.
winapi = { version = "0.3.9", features = ["winuser"] }
windows = { version = "0.58.0" }

[build-dependencies]
pest_generator = "2.7.15"
