## General
anyhow.workspace = true
async-trait.workspace = true
lazy_static.workspace = true
once_cell.workspace = true
ndarray.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
