[package]
name = "os_linux_apis"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - os_linux_apis"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "os_linux_apis" ]
publish.workspace = true
autolib = false

[dependencies]
# [add deps LATER](https://github.com/john-cd/rust_howto/issues/1303)
