[package]
name = "accessibility"
edition = "2024"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Book code examples for Accessibility using AccessKit and Winit."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["accessibility", "accesskit", "winit", "gui"]
categories = ["accessibility"]
publish.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
readme = "README.md"
autolib = false

[dependencies]
accesskit = "0.24.0"
accesskit_winit = "0.32.2"
winit = "0.30.13"
