[package]
name = "value_formatting"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - value_formatting"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["value-formatting"]
publish.workspace = true
autolib = false

[dependencies]
ryu = "1.0.19"
