[package]
name = "efghijkl"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - categories E to L"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

## Email
lettre = { version = "0.11.11", features = [ "tokio1-native-tls" ] }

## Embedded
# embassy = "0.0.0" # TODO P1 review installation / required dependencies

## Emulators

## Encoding
base64 = "0.22.1"
bytemuck = { version = "1.21.0", features = ["derive"] }
byteorder = "1.5.0"
data-encoding = "2.6.0"
form_urlencoded = "1.2.1"
monostate = "0.1.13"
percent-encoding = "2.3.1"
serde_json.workspace = true
toml = "0.8.19"
zerocopy = { version = "0.8.14", features = ["derive"] }

## External FFI
# TODO

## Filesystem
directories = "6.0.0"
glob = "0.3.1"
globset = "0.4.15"
memmap2 = "0.9.5"
notify = "8.0.0"
open = "5.3.0"
remove_dir_all = "1.0.0"
same-file = "1.0.6"
# tempdir = "0.3.7" # Outdated, replaced by tempfile
tempfile = "3.14.0"
walkdir.workspace = true

## Finance
RustQuant = "0.3"

## Game and friends
bevy = "0.15.1"
fyrox = "0.34.1"
fyrox-core = "0.28.1"
ggez = "0.9.3"
glam = "0.29.2"
macroquad = "0.4.13"

## Graphics
wgpu = "0.16.0" # pin for ggez

## GUI
arboard = "3.4.1"
cosmic-text = "0.12.1"
dioxus = "0.6.1"
dioxus-web = "0.6.1"
dioxus-desktop = "0.6.1"
# druid = "0.8.3" # TODO P3 review conflicts
eframe = "0.30.0"
egui = "0.30.0"
femtovg = "0.12.0"
# floem = "0.1.1" # TODO P3 review requirements
# gtk = { version = "0.9.5", package = "gtk4" } # Make sure to use gtk4; for relm4 / gtk4 examples
iced = "0.13.1"
minifb = "0.27.0"
pollster = "0.4" # for vello example
r3bl_tuify = "0.2.0"
# relm4 = "0.9.1"
# relm4-components = "0.9.1"
# # TODO https://gtk-rs.org/gtk4-rs/git/book/installation_linux.html
# # TODO https://gtk-rs.org/gtk4-rs/git/book/installation_windows.html
rfd = "0.15.2"
skia-safe = { version = "0.78", features = ["gl"] } # pin to 0.78 for slint
slint = "1.9.1"
taffy = "0.7.5"
tao = "0.31.1"
tauri = "2.0.6"      # Requires multiple libraries. See Dockerfile
vello = "0.3.0"
vger = "0.4.0"
# webrender = "0.61.0" # TODO P2 conflicts with RustQuant - native library `freetype`
winit = "0.30.8" # for vello, winit examples
xilem = "0.1.0"

## Hardware
num_cpus = "1.16.0"

## Internationalization
## TODO P2

## Localization
## TODO P2

## General
anyhow.workspace = true
csv = "1.3.1"
image = "0.25.5" # For image loading
serde.workspace = true
url.workspace = true
