[package]
name = "efghijkl"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - categories E to L"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## The dependencies that are NOT USED (YET) in examples are marked `optional = true`,
## in order to keep the compile speed decent.
## Remove the optional flag as needed.
[dependencies]

## Email
lettre = "0.11.10"

## Embedded
# embassy = { version = "0.0.0", optional  = true } # TODO P1 review installation / required dependencies

## Emulators

## Encoding
base64 = "0.22.1"
bytemuck = {version = "1.21.0", features = ["derive"] }
byteorder = "1.5.0"
data-encoding = "2.6.0"
form_urlencoded = "1.2.1"
monostate = "0.1.13"
percent-encoding = "2.3.1"
serde_json = "1.0.132"
toml = "0.8.19"
zerocopy = { version = "0.8.14", features = ["derive"] }

## External FFI
# TODO

## Filesystem
directories = "5.0.1"
glob = "0.3.1"
globset = "0.4.15"
memmap2 = "0.9.5"
notify = "7.0.0"
open = "5.3.0"
remove_dir_all = "1.0.0"
same-file = "1.0.6"
# tempdir = "0.3.7" # outdated, replaced by tempfile
tempfile = "3.14.0"
walkdir = "2.5.0"

## Finance
# RustQuant = { version = "0.3", optional = true } # TODO P3 review

## Game and friends
bevy = "0.15.1"

## Graphics
wgpu = "23.0.1"

## GUI
arboard = "3.4.1"
cosmic-text = "0.12.1"
# druid = { version = "0.8.3", optional = true } # TODO P3 review conflicts
eframe = "0.30.0"
egui = "0.30.0"
# floem = { version = "0.1.1", optional  = true } # TODO P3 review requirements
iced = "0.13.1"
leptos = "0.7.3"
r3bl_tuify = "0.2.0"
slint = "1.8.0"
tauri = "2.0.6" # requires multiple libraries. See Dockerfile
# xilem = { version = "0.1.0", optional = true } # TODO P3 review prerequisites

## Hardware
num_cpus = "1.16.0"

## Internationalization
## TODO

## Localization
## TODO

## General
anyhow = "1.0.94"
csv = "1.3.1"
serde = { version = "1.0.216", features = ["derive"] }
url = "2.5.4"
