[package]
license-file.workspace = true
name = "cryptography"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples for Cryptography including AES, RSA, and TLS implementations."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["cryptography", "encryption", "tls", "aes", "rsa", "security"]
categories = ["cryptography"]
publish.workspace = true
autolib = false

[dependencies]
aes-gcm = "0.10.3"
aes-gcm-siv = "0.11.1"
anyhow = "1.0.102"
argon2 = "0.5.3"
base64ct = "1.8.3"
bcrypt = "0.19.0"
chacha20poly1305 = "0.10.1"
clap = { version = "4.6.1", features = ["derive"] }
data-encoding = "2.11.0"
der = { version = "0.8.0", features = ["derive", "alloc"] }
digest = "0.11.2"
dsa = "0.6.3"
ecdsa = "0.16.9"
ed25519 = "2.2.3"
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
hyper = { version = "1.9.0", features = ["client"] }
hyper-tls = "0.6.0"
native-tls = "0.2.18"
p256 = { version = "0.13.2", features = ["pkcs8"] }
pem-rfc7468 = { version = "1.0.0", features = ["alloc"] }
pkcs8 = "0.11.0"
rand = "0.10.1"   # TODO was pinned because of ed25519
rand_core = { version = "0.6.4", features = ["getrandom"] } # TODO try upgrade from 0.6.4 to 0.10.1+
ring = "0.17.14"
rsa = "0.9.10"
rustls = "0.23.40"
scrypt = { version = "0.12.0", features = ["password-hash", "getrandom", "phc"] }
sha1 = "0.11.0"
signature = "3.0.0"
subtle = "2.6.1"
tokio-rustls = "0.26.4"
x509-cert = { version = "0.2.5", features = ["builder"] }
zeroize = "1.8.2"

[[example]]
name = "aead"
path = "examples/aead/main.rs"
test = true

[[example]]
name = "certs"
path = "examples/certs/main.rs"
test = true

[[example]]
name = "password_hashing"
path = "examples/password_hashing/main.rs"
test = true

[[example]]
name = "rsa"
path = "examples/rsa.rs"
test = true

[[example]]
name = "sign"
path = "examples/sign/main.rs"
test = true

[[example]]
name = "tls"
path = "examples/tls/main.rs"
test = true

[[example]]
name = "utilities"
path = "examples/utilities/main.rs"
test = true
