[package]
name = "os_unix_apis"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - os_unix_apis"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "os_unix_apis" ]
publish.workspace = true

[dependencies]
anyhow.workspace = true

[target.'cfg(target_family = "unix")'.dependencies]
nix = { version = "0.29.0", features = ["fs"] }
rustix = { version = "0.38.42", features = ["fs"] }
