[package]
name = "value_formatting"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - value_formatting"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["value_formatting"]
publish.workspace = true

[dependencies]
ryu = "1.0.19"
