[package]
name = "rendering_graphics_api"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - rendering_graphics_api"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "rendering_graphics_api" ]
publish.workspace = true
autolib = false

[dependencies]
# TODO P2
