[package]
name = "multimedia_audio"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - multimedia_audio"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "multimedia_audio" ]
publish.workspace = true
autolib = false

[dependencies]
