[package]
name = "database_implementations"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - database_implementations"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "database_implementations" ]
publish.workspace = true

[dependencies]
#meilisearch = "0.0.0"
meilisearch-sdk = "0.27.1"
tantivy = "0.22.0"
sled = "0.34.7"
surrealdb = { version = "2.1.4", features = [ "kv-mem" ] }

## General
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
anyhow.workspace = true
