[package]
name = "database_implementations"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - database_implementations"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["database_implementations"]
publish.workspace = true

[dependencies]
meilisearch-sdk = "0.27.1"
sled = "0.34.7"
surrealdb = { version = "2.1.4", features = ["kv-mem"] }
tantivy = "0.22.0"

## General
anyhow = "1.0.95"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }

[features]
# default = []
# surrealdb = ["dep:surrealdb"]
