[package]
name = "web_programming_websocket"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - web_programming_websocket"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["web_programming_websocket"]
publish.workspace = true
autolib = false

[dependencies]
async-tungstenite = { version = "0.29.1", features = [
    "tokio-runtime",
    "tokio-native-tls",
] }
# [async-tungstenite: review](https://github.com/john-cd/rust_howto/issues/1291)
tokio-tungstenite = "0.26.1"
tungstenite = "0.26.0"

## General
anyhow = "1.0.95"
futures-util = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
