[package]
name = "mathematics"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - mathematics"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["mathematics"]
publish.workspace = true
autolib = false

[dependencies]
anyhow = "1.0.102"
approx = "0.5.1" # was pinned at 0.4.0
clap = { version = "4.6.1", features = ["derive"] }
nalgebra = { version = "0.34.2", features = ["serde-serialize"] }
ndarray = { version = "0.17.2", features = [
    "approx",
] } # was pinned to 0.15.6 for linfa
num = "0.4.3"
num-bigint = "0.4.6"
num-traits = "0.2.19"
ordered-float = "5.3.0"
rust_decimal = "1.41.0"
rust_decimal_macros = "1.40.0"
serde_json = "1.0.149"
typenum = "1.20.0"

[target.'cfg(target_os = "linux")'.dependencies]
rug = "1.30.0"

[[example]]
name = "additional_numeric_types"
path = "examples/additional_numeric_types/main.rs"
test = true

[[example]]
name = "complex_numbers"
path = "examples/complex_numbers/main.rs"
test = true

[[example]]
name = "linear_algebra"
path = "examples/linear_algebra/main.rs"
test = true

[[example]]
name = "stats"
path = "examples/stats/main.rs"
test = true

[[example]]
name = "trigonometry"
path = "examples/trigonometry/main.rs"
test = true

