[package]
name = "development_tools_ffi"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - development_tools_ffi"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "development_tools_ffi" ]
# [fix categories in all Cargo.toml](https://github.com/john-cd/rust_howto/issues/1307)
publish.workspace = true
autolib = false

# FIXME
[dependencies]
# cxx = "1.0.136"
# flutter_rust_bridge = { version = "2.7.0", optional = true }
# jni = { version = "0.21.1", optional = true }
# napi = { version = "2.16.13", optional = true }
# neon = { version = "1.0.0", optional = true }
# magnus = { version = "0.7.1", optional = true }
mlua = { version = "0.11.2", features = ["lua54", "vendored"], optional = true }
# objc2 = { version = "0.6.0", optional = true }
# objc2-foundation = { version = "0.3.0", optional = true }
# objc2-app-kit = { version = "0.3.0", optional = true }
# rustler = { version = "0.36.0", optional = true }
# rutie = { version = "0.9.0", optional = true }
# uniffi = { version = "0.29", optional = true }

## General

[target.'cfg(target_os = "linux")'.dependencies]
pyo3 = "0.25.1" # was pinned to 0.21 to avoid conflict with `polars`

# FIXME
[build-dependencies]
bindgen = "0.72.0"
cbindgen = "0.29.0"
cc = "1.2"
# cxx-build = "1.0.136"
# uniffi = "0.29"

[features]
erlang = [] # FIXME "dep:rustler"
flutter = [] # FIXME "dep:flutter_rust_bridge"
java = [] # FIXME "dep:jni"
lua = ["dep:mlua"]
objc = [] # FIXME "dep:objc2", "dep:objc2-foundation", "dep:objc2-app-kit"
node = [] # FIXME "dep:napi", "dep:neon"
ruby = [] # FIXME "dep:magnus", "dep:rutie"

[package.metadata.cargo-machete]
ignored = ["cc", "bindgen", "cbindgen"]
