[package]
name = "finance"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - finance"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "finance" ]
publish.workspace = true
autolib = false

[dependencies]
#RustQuant = {version = "0.3", optional = true }
# [RustQuant: heavy build - polars, nalgebra, etc LATER](https://github.com/john-cd/rust_howto/issues/1313)

#[features]
#default = []
#rustquant = ["dep:RustQuant"]
