[package]
name = "external_ffi_bindings"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - external_ffi_bindings"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "external_ffi_bindings" ]
publish.workspace = true

[dependencies]
# TODO P2
