[package]
name = "tool_lib"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Tools & templates for the rust_howto book"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["markdown generation"]
categories = ["development-tools", "command-line-utilities", "text-processing"]
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
anyhow.workspace = true
crates_io_api = "0.11.0"
itertools = "0.14.0"
once_cell.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
similar = "2.6.0"
tera = "1.20.0"
tinytemplate = "1.2.1"
toml = "0.8.19"
tracing.workspace = true
trim-in-place = "0.1.7"

# Technically defining a target is not required, because cargo autodiscovers it,
# but useful during CI. See the Dockerfile.
[lib]
path = "src/lib.rs"
