[package]
name = "compression"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - compression"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["compression"]
publish.workspace = true
autolib = false

[dependencies]
flate2 = "1.1.0"
tar = "0.4.43"
# [add zip async_zip](https://github.com/john-cd/rust_howto/issues/1262)

## General
anyhow = "1.0.95"
