[package]
name = "compression"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - compression"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["compression"]
publish.workspace = true
autolib = false

[dependencies]
flate2 = "1.1.2"
tar = "0.4.43"
zip = "4.5.0"

# General
anyhow = "1.0.95"

# TODO add example for async_zip?
# async_zip = "0.0.17"

# FIXME finish async_compresssion example
# bytes = "1.9.0"
# futures = "0.3.31"
# tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
# tokio-util = { version = "0.7.13", features = ["codec"] }
