[package]
name = "graphics"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - graphics"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "graphics" ]
publish.workspace = true

[dependencies]
wgpu = "0.16.0" # pin for ggez
