[package]
name = "stuv"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## The dependencies that are NOT USED (YET) in examples are marked `optional = true`,
## in order to keep the compile speed decent.
## Remove the optional flag as needed.
[dependencies]

## Science - Machine Learning
candle-core = { version = "0.8", optional = true }
linfa = { version = "0.7.0", optional = true }
watchmaker = { version = "2.0.0", optional = true }

## Science - Robotics
openrr = { version = "0.1.0", optional = true } # requires `libudev-dev`
zenoh = { version = "1.0.2", optional = true }

## Template engine

## Text processing
regex = "1.11.1"
unicode-segmentation = "1.12.0"

## Value formatting

## Virtualization

## Visualization
plotly = { version = "0.11.0", optional = true }

anyhow = "1.0.91"
lazy_static = "1.5.0"
once_cell = "1.20.2"

[features]

## Dependencies that are CURRENTLY unused in the examples (marked as optional above)
## You may check for conflicts with: cargo build --features unused or cargo build --all-features
unused = [
    "dep:candle-core",
    "dep:linfa",
    "dep:openrr",
    "dep:plotly",
    "dep:watchmaker",
    "dep:zenoh",
]
