[package]
name = "d"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## The dependencies that are NOT USED (YET) in examples are marked `optional = true`,
## in order to keep the compile speed decent.
## Remove the optional flag as needed.
[dependencies]

## Data structures
arrayvec = "0.7.6"
bitflags = "2.6.0"
bytes = "1.9.0"
dashmap = "6.1.0"
flagset = "0.4.6"
indexmap = "2.7.0"
linked-hash-map = "0.5.6"
multimap = "0.10.0"
#petgraph = "0.7.0" # TODO
slotmap = "1.0.7"
smallvec = "2.0.0-alpha.8"
tinyvec = { version = "1.8.1", features = ["alloc"] }
uuid = { version = "1.11.0", features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
] }

## Database and friends
cornucopia = "0.9.0"
deadpool = "0.12.1"
deadpool-postgres = { version = "0.14.1", features = [
    "serde",
] }
diesel = { version = "2.2.6", features = ["sqlite"] }
diesel_migrations = { version = "2.2.0", features = ["sqlite"] }
elasticsearch = "8.17.0-alpha.1" # NOTE: alpha version
#meilisearch = "0.0.0"
meilisearch-sdk = "0.27.1"
mongodb = "3.1.1"
postgres = "0.19.9"
sea-orm = "1.1.3"
seaography = "1.1.2"
sled = "0.34.7"
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite", "macros" ] }
surrealdb = { version = "2.1.4", features = [ "kv-mem" ] }
tantivy = "0.22.0"
tokio-postgres = "0.7.12"
redis = "0.27.6"

## Date and time
chrono = "0.4.39"
time = { version = "0.3.37" }

## Dev Tools
# TODO bacon = { version = "3.2.0", optional = true }
crates_io_api = "0.11.0"
cross = "0.2.5"
doc-comment = "0.3.3"
kani = "0.0.1"
# TODO
# mdbook
# mdbook-cmdrun
# mdbook-journal
# mdbook-keeper
# mdbook-linkcheck
# mdbook-pagetoc
# mdbook-private
# mdbook-tera
# mdbook-theme
# mdbook-toc
# miri
semver = "1.0.24"
# termbook = "1.4.2" # requires mdbook; TODO P3 review pre-requisites
yapp = "0.4.1"

## Dev Tools: cargo plugins
# TODO
# cargo
# cargo-auditable
# cargo-cache
# cargo-edit
# cargo-hack
# cargo-husky
# cargo-make
# cargo-nextest
# cargo-tarpaulin
# cargo-udeps
xshell = { version = "0.2.7" }

## Dev. Tools FFI
cxx = "1.0.136"
bindgen = "0.71.1"
cbindgen = "0.27.0"

## Dev Tools: Debugging
env_logger = "0.11.6"
log = "0.4.22"
log4rs = "1.3.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

## Dev Tools: Proc Macros
darling = "0.20.10"
paste = "1.0.15"
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = { version = "2.0.92", features = ["full"] }
watt = "0.5.0"

## Dev Tools: Profiling
criterion = "0.5.1"
dhat = "0.3.3"
divan = "0.1.17"

## Dev Tools: Testing
afl = "0.15.13"
approx = "0.5.1"
anyhow = "1.0.95"
insta = "1.41.1"

## General
dotenvy = "0.15.7"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10.68", features = ["vendored"] }
rusqlite = { version = "0.32.1", features = ["chrono"] }
syslog = "7.0.0"

[dev-dependencies]
## Used for testing
rusty-fork = "0.3.0"

[build-dependencies]
cc = "1.2.6"

[features]

## Dependencies that are CURRENTLY unused in the examples (marked as optional above)
## You may check for conflicts with: cargo build --features unused or cargo build --all-features
unused = [
    #"dep:cornucopia",
    #"dep:dashmap",
    #"dep:doc-comment",
    #"dep:kani",
    #"dep:linked-hash-map",
    #"dep:paste",
    #"dep:petgraph",
    #"dep:proc-macro2",
    #"dep:quote",
    #"dep:seaography",
    #"dep:sea-orm",
    #"dep:syn",
    #"dep:tantivy",
    #"dep:time",
    #"dep:watt",
    #"dep:xshell",
    #"dep:yapp",
]
# TODO
