[package]
name = "standard_library"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Core examples demonstrating idiomatic use of the Rust standard library and common error handling patterns."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["std", "standard-library", "thiserror", "derive_more"]
categories.workspace = true
publish = false
autolib = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
anyhow = "1.0.102"
derive_more = { version = "2.1.1", features = ["full"] }
thiserror = "2.0.18"
