[package]
name = "data_structures"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - data_structures"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["data-structures"]
publish.workspace = true
autolib = false

[dependencies]
anyhow = "1.0.102"
arrayvec = "0.7.6"
bitflags = "2.11.1"
bitvec = "1.0.1"
bloomfilter = "3.0.1"
bytes = "1.11.1"
clap = { version = "4.6.1", features = ["derive"] }
crates_io_api = "0.12.0"
flagset = "0.4.7"
fnv = "1.0.7"
heapless = "0.9.3" # TODO pinned elsewhere to 0.7.17 for postcard
indexmap = "2.14.0"
linked-hash-map = "0.5.6"
multimap = "0.10.1"
petgraph = "0.8.3"
priority-queue = "2.7.0"
rangemap = "1.7.1"
roaring = "0.11.4"
skiplist = "1.1.0"
slotmap = "1.1.1"
smallvec = "1.15.1" # alpha
tinyvec = { version = "1.11.0", features = ["alloc"] }
ulid = "1.2.1"
uuid = { version = "1.23.1", features = [
    # Lets us generate random UUIDs.
    "v4",
    # Use a faster (but still sufficiently random) RNG.
    "fast-rng",
    # Enable better diagnostics for compile-time UUIDs.
    "macro-diagnostics",
] }

[[example]]
name = "binaryheap"
path = "examples/binaryheap/main.rs"
test = true

[[example]]
name = "bitfield"
path = "examples/bitfield/main.rs"
test = true

[[example]]
name = "bloomfilter"
path = "examples/bloomfilter/main.rs"
test = true

[[example]]
name = "btrees"
path = "examples/btrees/main.rs"
test = true

[[example]]
name = "graph"
path = "examples/graph/main.rs"
test = true

[[example]]
name = "hashmap"
path = "examples/hashmap/main.rs"
test = true

[[example]]
name = "linkedlist"
path = "examples/linkedlist/main.rs"
test = true

[[example]]
name = "maps"
path = "examples/maps/main.rs"
test = true

[[example]]
name = "rangemap"
path = "examples/rangemap/main.rs"
test = true

[[example]]
name = "skiplist"
path = "examples/skiplist/main.rs"
test = true

[[example]]
name = "stack_allocated"
path = "examples/stack_allocated/main.rs"
test = true

[[example]]
name = "stacks_and_queues"
path = "examples/stacks_and_queues/main.rs"
test = true

[[example]]
name = "strings"
path = "examples/strings/main.rs"
test = true

[[example]]
name = "unique_ids"
path = "examples/unique_ids/main.rs"
test = true

[[example]]
name = "vector"
path = "examples/vector/main.rs"
test = true

