[package]
name = "cryptography_cryptocurrencies"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - cryptography_cryptocurrencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["cryptography::cryptocurrencies"]
publish.workspace = true
autolib = false

[dependencies]
# LATER

[[example]]
name = "cryptocurrencies"
path = "examples/cryptocurrencies/main.rs"
test = true
