[package]
name = "network_programming"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - network_programming"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["network_programming"]
publish.workspace = true
autolib = false

[dependencies]
# axum = { version = "0.8.4", features = ["tokio"] }
# tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"]  }
# url = "2.5.4"
anyhow = "1.0.100"
# FIXME ngrok = { version = "0.15.0", features = [ "axum" ] }
pingora = { version = "0.8.0", features = ["lb"] }

[target.'cfg(target_os = "linux")'.dependencies]
glommio = "0.9.0"
