[package]
name = "network_programming"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - network_programming"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["network_programming"]
publish.workspace = true
autolib = false

[dependencies]
hyper = "1.6.0"
ngrok = "0.14.0"
# TODO pingora = "0.4.0"
tokio = { version = "1.44.2", features = ["full"] }

[target.'cfg(target_os = "linux")'.dependencies]
glommio = "0.9.0"

[features]
default = []
# ngrok = ["dep:ngrok"]
# pingora = ["dep:pingora"]
