[package]
name = "network_programming"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - network_programming"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["network_programming"]
publish.workspace = true
autolib = false

[dependencies]
ngrok = { version = "0.15.0", features = [ "axum" ] }
pingora = { version = "0.4.0", features = [ "lb" ] }  # NOTE: requires `sfv` patch in the workspace Cargo.toml

## General
anyhow = "1.0.95"
async-trait = "0.1.85"
axum = { version = "0.8.1", features = ["tokio"] }
tokio = { version = "1.44.2", features = ["full"] }
url = "2.5.4"

[target.'cfg(target_os = "linux")'.dependencies]
glommio = "0.9.0"

#[features]
#default = []
