[package]
name = "embedded"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - embedded"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["embedded"]
publish.workspace = true
autolib = false

[dependencies]

[dev-dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embassy = { git = "https://github.com/embassy-rs/embassy", branch = "main", features = [
    "alloc",
    "std",
] }
panic-halt = "0.2"

#[features]
# default = []
