## Command-line utilities
# starship = "1.21.1" # TODO P2 do we need?

## General
anyhow.workspace = true
chrono = "0.4.39"
crates-io = "0.40.6"
dashmap = "6.1.0"
data-encoding = "2.6.0"
glob = "0.3.1"
hex-literal = "0.4"
hyper = "1.5.2"
hyper-tls = "0.6.0"
image = "0.25.5"
itertools = "0.14.0"
lazy_static.workspace = true
num = "0.4.3"
num_cpus = "1.16.0"
rand.workspace = true
serde.workspace = true
serde_derive = "1.0.216"
time = "0.3.37"
tokio.workspace = true
walkdir.workspace = true
