# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

## General
axum = "0.8.1"
dotenvy = "0.15.7"
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
