[package]
name = "mn"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - categories M and N"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

## Math
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
ndarray = { workspace = true, features = ["approx"] }
num = "0.4.3"
num-bigint = "0.4.6"
num-traits = "0.2.19"
ordered-float = "4.6.0"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"

## Memory management
lazy_static.workspace = true
once_cell.workspace = true

## Multimedia and friends
# TODO

## Network Programming
pingora = "0.4.0"

## No std and no alloc
# TODO

# General
anyhow.workspace = true
approx.workspace = true
serde_json.workspace = true
hyper = "1.5.2"
tokio.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
rug = "1.26.1"
