[package]
name = "mn"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

## Math
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
ndarray = { version = "0.16.1", features = ["approx"] }
num = "0.4.3"
num-bigint = "0.4.6"
num-traits = "0.2.19"
ordered-float = "4.6.0"

## Memory management
once_cell = "1.20.2"
serde_json = "1.0.133"

## Multimedia and friends

## Network Programming

## No std and no alloc

# General
anyhow = "1.0.94"
approx = "0.5.1"
lazy_static = "1.5.0"

[features]

## Dependencies that are CURRENTLY unused in the examples (marked as optional above)
## You may check for conflicts with: cargo build --features unused or cargo build --all-features
unused = [
]
