[package]
name = "mn"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - categories M and N"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

## Math
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
ndarray = { version = "0.16.1", features = ["approx"] }
num = "0.4.3"
num-bigint = "0.4.6"
num-traits = "0.2.19"
ordered-float = "4.6.0"
rug = "1.26.1"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"

## Memory management
lazy_static = "1.5.0"
once_cell = "1.20.2"

## Multimedia and friends
# TODO

## Network Programming
# TODO

## No std and no alloc
# TODO

# General
anyhow = "1.0.94"
approx = "0.5.1"
serde_json = "1.0.133"
