[package]
license-file.workspace = true
name = "emulators"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - emulators"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["emulators"]
publish.workspace = true
autolib = false

[dependencies]
polkavm = "0.33.1"

[[example]]
name = "emulators"
path = "examples/emulators/main.rs"
test = true
