[package]
name = "rendering_engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - rendering_engine"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["rendering::engine"]
publish.workspace = true
autolib = false

[dependencies]

[[example]]
name = "rendering_engines"
path = "examples/rendering_engines/main.rs"
test = true
