[package]
name = "finance"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - finance"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "finance" ]
publish.workspace = true

[dependencies]
#RustQuant = "0.3" # TODO P2 heavy build (polars, nalgebra, etc)

[features]
#default = []
#rustquant = ["dep:RustQuant"]
