[package]
name = "embedded"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - embedded"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "embedded" ]
publish.workspace = true
autolib = false

[dependencies]
# embassy = "0.0.0" # TODO P1 review installation / required dependencies

[features]
#default = []
