use anyhow::Result;
use serde::Serialize;

/// Markdown badges i.e. a small image (generated by shields.io)
/// linked to a website In this case, badges linked to docs.rs,
/// crates.io, github, and lib.rs
pub(super) static CRATE_BLOCK_BADGES: &str = concat!(
    "{{ if homepage_defined }}[![{crate_name}~website][c~{crate_name}~website~badge]][c~{crate_name}~website] {{ endif }}",
    "[![{crate_name}][c~{crate_name}~docs~badge]][c~{crate_name}~docs] ",
    "[![{crate_name}~crates.io][c~{crate_name}~crates.io~badge]][c~{crate_name}~crates.io] ",
    "{{ if repository_defined }}[![{crate_name}~repo][c~{crate_name}~repo~badge]][c~{crate_name}~repo] {{ endif }}",
    r"[![{crate_name}~lib.rs][c~{crate_name}~lib.rs~badge]][c~{crate_name}~lib.rs]\{\{hi:{crate_name}}} "
);

pub(super) static CRATE_DESCRIPTION: &str =
    "{{- if description_defined }}{description}{{ endif -}}";

/// Reference definitions for the badges above
pub(super) static CRATE_BLOCK_REFDEFS: &str = "\
[c~{crate_name}~crates.io]: https://crates.io/crates/{crate_name}
[c~{crate_name}~crates.io~badge]: https://img.shields.io/badge/crates.io-{crate_name | shielded}-crimson
[c~{crate_name}~docs]: {{ if documentation_defined }}{documentation}{{ else }}https://docs.rs/{crate_name}{{ endif }}
[c~{crate_name}~docs~badge]: https://img.shields.io/crates/v/{crate_name}?label={crate_name}
{{ if repository_defined }}[c~{crate_name}~repo]: {repository}
[c~{crate_name}~repo~badge]: https://img.shields.io/badge/{crate_name | shielded}-steelblue?logo=github{{ endif }}
[c~{crate_name}~lib.rs]: https://lib.rs/crates/{crate_name}
[c~{crate_name}~lib.rs~badge]: https://img.shields.io/badge/lib.rs-{crate_name | shielded}-yellow
{{ if homepage_defined }}[c~{crate_name}~website]: {homepage}
[c~{crate_name}~website~badge]: https://img.shields.io/badge/{crate_name | shielded}-coral{{ endif }}
[c~{crate_name}~recent-downloads~badge]: https://img.shields.io/crates/dr/{crate_name}
[c~{crate_name}~deps-rs~badge]: https://img.shields.io/deps-rs/{crate_name}/latest
[c~{crate_name}~license~badge]: https://img.shields.io/crates/l/{crate_name}
[c~{crate_name}~dependents~badge]: https://img.shields.io/crates/dependents/{crate_name}
{{ if github_detected }}[c~{crate_name}~commit-activity~badge]: https://img.shields.io/github/commit-activity/y/{github_user}/{github_repo}
[c~{crate_name}~last-commit~badge]: https://img.shields.io/github/last-commit/{github_user}/{github_repo}{{ endif }}
";

/// The different modes for generating content related to a crate.
///
/// This enum defines the different types of content that can be generated for a crate, such as badges, description, and reference definitions.
pub enum GenerationMode {
    CrateBlock,
    CrateDescription,
    CrateBlockRefdefs,
}

/// Generates crate block badges, description, or reference definitions based on the provided crate data and generation mode.
///
/// # Arguments
///
/// * `crate_data` - A reference to the `crates_io_api::Crate` struct containing information about the crate.
pub fn create_crate_block_badges_or_refdefs(
    crate_data: &crates_io_api::Crate,
    mode: GenerationMode,
) -> Result<String> {
    use trim_in_place::TrimInPlace;

    use super::detect_github_url;
    use super::normalize_docs_url;

    let tt = super::get_template_engine()?;

    // Normalize URL:
    let documentation = crate_data
        .documentation
        .as_ref()
        .map(|s| normalize_docs_url(s))
        .unwrap_or_default();

    let repository: String = crate_data
        .repository
        .as_deref()
        .unwrap_or_default()
        .replace(".git", "");

    let (github_detected, github_user, github_repo) = detect_github_url(&repository);

    #[derive(Serialize)]
    /// Context data used for rendering templates.
    struct Context<'a> {
        crate_name: &'a str,
        description_defined: bool,
        description: &'a str,
        documentation_defined: bool,
        documentation: &'a str, // URL e.g. https://docs.rs/{crate}
        homepage_defined: bool,
        homepage: &'a str, /* URL e.g. https://github.com/sollimann/bonsai, https://serde.rs */
        repository_defined: bool,
        repository: &'a str,   // URL e.g. https://github.com/serde-rs/serde
        github_detected: bool, // The repository is hosted on GitHub.
        github_user: &'a str,
        github_repo: &'a str,
    }

    let context = Context {
        crate_name: &crate_data.name.to_lowercase(),
        description_defined: crate_data.description.is_some(),
        description: crate_data.description.as_deref().unwrap_or_default(),
        documentation_defined: crate_data.documentation.is_some(),
        documentation: documentation.trim_end_matches('/'),
        homepage_defined: crate_data.homepage.is_some()
            && (crate_data.homepage != crate_data.repository),
        homepage: crate_data
            .homepage
            .as_deref()
            .unwrap_or_default()
            .trim_end_matches('/'),
        repository_defined: crate_data.repository.is_some(),
        repository: repository.trim_end_matches('/'),
        github_detected,
        github_user,
        github_repo,
    };
    let mut rendered = match mode {
        GenerationMode::CrateBlock => tt.render("CRATE_BLOCK_BADGES", &context)?,
        GenerationMode::CrateDescription => tt.render("CRATE_DESCRIPTION", &context)?,
        GenerationMode::CrateBlockRefdefs => tt.render("CRATE_BLOCK_REFDEFS", &context)?,
    };
    rendered.trim_in_place();
    Ok(rendered)
}

/// Capitalizes the first letter of a string if it is not equal to another string.
///
/// # Arguments
///
/// * `s` - The string to capitalize.
/// * `should_not_be` - The string that `s` should not be equal to.
fn capitalize_if_not(s: String, should_not_be: &str) -> String {
    if s != should_not_be {
        let mut c = s.chars();
        match c.next() {
            None => String::new(),
            Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        }
    } else {
        s
    }
}

/// Creates a crate page section for use in the `crates_and_examples.md` index page.
///
/// Each section includes:
/// - An H3 header with an anchor: `### \`{name}\` {#{name}}`
/// - Badges for docs.rs, crates.io, GitHub repo, and lib.rs
/// - Keyword index entries (`{{hi:...}}`)
/// - Category badges
/// - An empty recipe table placeholder
///
/// # Arguments
///
/// * `name` - The name of the crate.
///
/// Returns the generated markdown section as a `String`.
pub fn create_crate_page_section(name: &str) -> Result<String> {
    use anyhow::Context;

    let mut section = String::new();

    // H3 header with anchor
    section.push_str(&format!("### `{name}` {{#{name}}}\n\n"));

    let info =
        crate::get_info_for_crate(name).with_context(|| format!("Unknown crate: {name}"))?;

    // Badges for docs.rs, crates.io, repo, lib.rs
    let badges =
        create_crate_block_badges_or_refdefs(&info.crate_data, GenerationMode::CrateBlock)?;
    section.push_str(&badges);

    // Keyword index anchors
    let keywords: Vec<_> = info
        .keywords
        .into_iter()
        .map(|k| capitalize_if_not(k.keyword, name))
        .collect();
    let kws = keywords.iter().map(String::as_str).collect();
    let markdown = super::create_index_anchors(kws)?;
    section.push_str(&markdown);

    // Category badges
    for cat in info.categories {
        let markdown = super::create_category_badge(&cat.category, &cat.slug)?;
        section.push_str(&markdown);
    }
    section.push_str("\n\n");

    // Empty recipe table placeholder
    section.push_str("| Recipe |\n|--------|\n");

    Ok(section)
}

/// Creates a "crate block" for a given crate, which includes several badges linking to various crate websites; associated keywords, categories; crate description,
/// and reference definitions for all links.
///
/// # Arguments
///
/// * `name` - The name of the crate.
///
/// Returns the crate block as a `String`.
/// Also return the reference definitions as a separate vector of strings.
pub fn create_crate_block(name: &str) -> Result<(String, Vec<String>)> {
    use anyhow::Context;

    use super::remove_empty_lines;

    let mut crate_block = String::new();

    let info = crate::get_info_for_crate(name).with_context(|| format!("Unknown crate: {name}"))?;

    let badges =
        create_crate_block_badges_or_refdefs(&info.crate_data, GenerationMode::CrateBlock)?;
    crate_block.push_str(&badges);

    // Add index entries for keywords.
    let keywords: Vec<_> = info
        .keywords
        .into_iter()
        .map(|k| capitalize_if_not(k.keyword, name))
        .collect();
    let kws = keywords.iter().map(String::as_str).collect();
    let markdown = super::create_index_anchors(kws)?;
    crate_block.push_str(&markdown);

    // Print category badges.
    for cat in info.categories {
        let markdown = super::create_category_badge(&cat.category, &cat.slug)?;
        crate_block.push_str(&markdown);
    }
    crate_block.push_str("\n\n");

    let desc =
        create_crate_block_badges_or_refdefs(&info.crate_data, GenerationMode::CrateDescription)?;
    if !desc.is_empty() {
        crate_block.push_str(&(format!("{desc}\n\n")));
    }

    let (vector_of_lines, refdefs) = remove_empty_lines(&create_crate_block_badges_or_refdefs(
        &info.crate_data,
        GenerationMode::CrateBlockRefdefs,
    )?);
    crate_block.push_str(&refdefs);

    // Also return the refdefs as a separate vector of strings.
    Ok((crate_block, vector_of_lines))
}

/// The regex pattern for matching `{{#crate crate_name}}` directives.
///
/// Matches the following variations:
/// - `{{#crate crt}}`
/// - `{{#crate crt }}`
/// - `{{#crate: crt}}`
/// - `{{#crate : crt}}`
/// - `{{#crate x_y-z}}`
/// - `{{#crate: crt cat1 cat-2 }}` (crate name with optional additional words)
const CRATE_BLOCK_DIRECTIVE_REGEX: &str = r"\{\{\s*#crate\s*:?\s+([^\s}]+)[^}]*\}\}";

/// Lazily compiled regex for `{{#crate crate_name}}` directives.
/// Compiled only once and reused across all calls.
static CRATE_BLOCK_RE: once_cell::sync::Lazy<regex::Regex> =
    once_cell::sync::Lazy::new(|| {
        regex::Regex::new(CRATE_BLOCK_DIRECTIVE_REGEX)
            .expect("CRATE_BLOCK_DIRECTIVE_REGEX is a valid regex")
    });

/// Expand all `{{#crate crate_name}}` directives in the given content string.
///
/// For each `{{#crate crate_name}}` directive found, fetches crate information
/// from crates.io and replaces the directive with the full crate block markdown
/// (badges, keywords, categories, description, and reference definitions).
///
/// Directives for which crate information cannot be fetched are left unchanged,
/// so that `mdbook-scrub` can clean them up later.
///
/// # Arguments
///
/// * `content` - The markdown content to process.
///
/// # Returns
///
/// A tuple `(expanded_content, refdefs)` where:
/// - `expanded_content` is the content with directives replaced.
/// - `refdefs` is a `Vec` of reference definition strings (one per non-empty
///   line from all expanded crate blocks), suitable for merging into a
///   `refs` file.
pub fn process_crate_block_directives(content: &str) -> Result<(String, Vec<String>)> {
    use std::collections::HashMap;
    use std::collections::HashSet;

    use regex::Captures;

    let re = &*CRATE_BLOCK_RE;

    // Collect unique crate names from all directives in the content.
    let crate_names: HashSet<String> = re
        .captures_iter(content)
        .map(|caps| caps[1].trim().to_string())
        .collect();

    if crate_names.is_empty() {
        return Ok((content.to_string(), vec![]));
    }

    // Pre-fetch crate data for all unique crate names.
    // This avoids repeated API calls when the same crate appears multiple times.
    let mut cache: HashMap<String, String> = HashMap::new();
    let mut all_refdefs: Vec<String> = Vec::new();

    for name in &crate_names {
        match create_crate_block(name) {
            Ok((block, refdefs)) => {
                all_refdefs.extend(refdefs);
                cache.insert(name.clone(), block);
            }
            Err(e) => {
                tracing::warn!("Failed to generate crate block for '{name}': {e}");
            }
        }
    }

    // Replace directives with the pre-fetched crate block content.
    // If crate lookup failed, leave the original directive unchanged.
    let new_content = re.replace_all(content, |caps: &Captures| {
        let name = caps[1].trim();
        cache
            .get(name)
            .cloned()
            .unwrap_or_else(|| caps[0].to_string())
    });

    Ok((new_content.into_owned(), all_refdefs))
}

/// Walk a directory tree, expand all `{{#crate crate_name}}` directives found
/// in `.md` files, and optionally merge the collected reference definitions
/// into a refdefs file.
///
/// For each Markdown file that contains one or more `{{#crate crate_name}}`
/// directives, the file is backed up and overwritten with the expanded content.
///
/// # Arguments
///
/// * `dir` - Root directory to walk recursively.
/// * `refdefs_file` - Optional path to a refdefs file where the collected
///   reference definitions will be merged.
pub fn expand_crate_block_directives_in_directory(
    dir: &std::path::Path,
    refdefs_file: Option<&std::path::Path>,
) -> Result<()> {
    use std::ffi::OsStr;

    use walkdir::WalkDir;

    let re = &*CRATE_BLOCK_RE;
    let mut all_refdefs: Vec<String> = Vec::new();

    for entry in WalkDir::new(dir) {
        let entry = entry?;
        let path = entry.path();

        // Only process Markdown files.
        if path.extension() != Some(OsStr::new("md")) {
            continue;
        }

        let content = std::fs::read_to_string(path)?;

        // Skip files that do not contain any `{{#crate }}` directives.
        if !re.is_match(&content) {
            continue;
        }

        tracing::info!("Processing '{}'", path.display());
        let (new_content, refdefs) = process_crate_block_directives(&content)?;
        all_refdefs.extend(refdefs);

        // Only write back if the content actually changed.
        if new_content != content {
            crate::backup_then_write_to(path, new_content)?;
        }
    }

    // Merge all collected refdefs into the refdefs file, if one was provided.
    if let Some(refdefs_path) = refdefs_file {
        crate::merge(refdefs_path, all_refdefs)?;
    }

    Ok(())
}

#[cfg(test)]
mod directive_tests {
    use super::CRATE_BLOCK_RE;

    /// Helper: test that the regex captures the expected crate name from `input`.
    fn assert_captures_crate_name(input: &str, expected_name: &str) {
        let re = &*CRATE_BLOCK_RE;
        let caps = re.captures(input).unwrap_or_else(|| {
            panic!("Expected regex to match '{input}'");
        });
        assert_eq!(caps[1].trim(), expected_name, "input = {input:?}");
    }

    /// Helper: test that the regex does NOT match `input`.
    fn assert_no_match(input: &str) {
        let re = &*CRATE_BLOCK_RE;
        assert!(
            re.captures(input).is_none(),
            "Expected regex NOT to match '{input}'"
        );
    }

    #[test]
    fn test_simple_crate_directive() {
        assert_captures_crate_name("{{#crate crt}}", "crt");
    }

    #[test]
    fn test_crate_directive_trailing_space() {
        assert_captures_crate_name("{{#crate crt }}", "crt");
    }

    #[test]
    fn test_crate_directive_colon() {
        assert_captures_crate_name("{{#crate: crt}}", "crt");
    }

    #[test]
    fn test_crate_directive_space_colon_space() {
        assert_captures_crate_name("{{#crate : crt}}", "crt");
    }

    #[test]
    fn test_crate_directive_hyphen_underscore() {
        assert_captures_crate_name("{{#crate x_y-z}}", "x_y-z");
    }

    #[test]
    fn test_crate_directive_with_additional_categories() {
        assert_captures_crate_name(
            "{{#crate: crt cat1 cat-2 cat-2-2 cat3::sub-cat-3 }}",
            "crt",
        );
    }

    #[test]
    fn test_no_match_missing_crate_name() {
        assert_no_match("{{#crate}}");
        assert_no_match("{{#crate }}");
    }

    #[test]
    fn test_no_match_example_directive() {
        assert_no_match("{{#example some_example}}");
    }

    #[test]
    fn test_multiple_directives_in_content() {
        let re = &*CRATE_BLOCK_RE;
        let content = "See {{#crate serde}} and {{#crate: anyhow }}.";
        let names: Vec<&str> = re
            .captures_iter(content)
            .map(|c| c.get(1).unwrap().as_str().trim())
            .collect();
        // Order depends on iteration; just check both are present.
        assert!(names.contains(&"serde"), "expected 'serde' in {names:?}");
        assert!(names.contains(&"anyhow"), "expected 'anyhow' in {names:?}");
    }

    #[test]
    fn test_process_crate_block_directives_no_directives() {
        let content = "# Hello\n\nNo directives here.\n";
        let result = super::process_crate_block_directives(content);
        assert!(result.is_ok());
        let (out, refdefs) = result.unwrap();
        assert_eq!(out, content);
        assert!(refdefs.is_empty());
    }
}
