[package]
name = "rendering_graphics_api"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples for low-level Rendering Graphics APIs like WGPU."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["rendering", "graphics", "wgpu", "gpu", "api"]
categories = [ "rendering::graphics-api" ]
publish.workspace = true
autolib = false

[dependencies]
wgpu = { version = "29.0.3", optional = true } # was pinned for ggez

[features]
default = []
wgpu = ["dep:wgpu"]
