[package]
name = "tools"
version = "0.1.0"
edition = "2021"
publish=false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
heck = "0.4.1"
once_cell = "1.19.0"
quick-xml = "0.31.0"
regex = "1.10.2"
url = "2.5.0"
walkdir = "2.4.0"
