[workspace]
resolver = "3"
members = ["clean", "crate_indices", "mdbook-scrub", "templ", "tool_lib"]

# Default values for packages in the workspace
[workspace.package]
version = "0.1.2"
authors = ["John CD"]
edition = "2024"
rust-version = "1.90"
description = "Internal tooling for managing the Rust How-to book, including cleaning, templating, and link scrubbing."
documentation = "https://docs.rs/rust_howto/"
homepage = "https://john-cd.com/rust_howto/"
repository = "https://github.com/john-cd/rust_howto/tools/"
keywords = ["rust-howto", "tooling", "mdbook", "automation", "preprocessor"]
categories = ["development-tools"]
publish = false
