[package]
name = "gui"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - gui"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["gui"]
publish.workspace = true
autolib = false

[dependencies]
arboard = "3.4.1"
cosmic-text = "0.13.2"
dioxus = { version = "0.6.1", optional = true }
dioxus-web = { version = "0.6.1", optional = true }
dioxus-desktop = { version = "0.6.1", optional = true }
eframe = "0.31.0"
egui = "0.31.0"
femtovg = { version = "0.13.0", optional = true }
# floem = { version = "0.2.0", optional = true } # FIXME P3 review requirements
# gtk = { version = "0.9.5", package = "gtk4", optional = true } # FIXME Make sure to use gtk4; for relm4 / gtk4 examples
iced = { version = "0.13.1", optional = true }
minifb = "0.28.0"
morphorm = "0.6.5"
pollster = { version = "0.4", optional = true } # for vello example
r3bl_tuify = "0.2.0"
# relm4 = { version = "0.9.1", optional = true }
# relm4-components = { version = "0.9.1", optional = true }
# # FIXME P1 https://gtk-rs.org/gtk4-rs/git/book/installation_linux.html
# # FIXME P1 https://gtk-rs.org/gtk4-rs/git/book/installation_windows.html
rfd = "0.15.2"
skia-safe = { version = "0.82.0", features = [
    "gl",
], optional = true } # pin to 0.78 for slint
slint = "1.9.1"
taffy = "0.7.5"
tao = "0.32.8"
tauri = "2.0.6" # Requires multiple libraries. See Dockerfile
vello = { version = "0.4.0", optional = true }
vger = { version = "0.4.0", optional = true }
# vizia = { version = "0.2.0", optional = true } # FIXME P1 conflict with skia-safe
# webrender = { version = "0.61.0", optional = true } # FIXME P2 conflicts with RustQuant - native library `freetype`
winit = "0.30.8"                               # for vello, winit examples
xilem = { version = "0.1.0", optional = true }

## General
anyhow = "1.0.95"

[features]
default = []
dioxus = ["dep:dioxus", "dep:dioxus-web", "dep:dioxus-desktop"]
#egui = ["dep:eframe", "dep:egui"]
femtovg = ["dep:femtovg"]
#gtk = ["dep:gtk", "dep:relm4", "dep:relm4-components"]
iced = ["dep:iced"]
skia = ["dep:skia-safe"]
#slint = ["dep:slint"]
#tauri = ["dep:tauri"]
vger = ["dep:vger"]
vello = ["dep:pollster", "dep:vello"]
#webrender = ["dep:webrender"]
xilem = ["dep:xilem"]
#vizia = ["dep:vizia"]
