[package]
name = "other"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## The dependencies that are NOT USED (YET) in examples are marked `optional = true`,
## in order to keep the compile speed decent.
## Remove the optional flag as needed.
[dependencies]

## Cloud
aws-config = "1.5.13"
aws-sdk-s3 = "1.68.0"
lambda_runtime = "0.13.0"

## Cross platform
crux_core = "0.10.1"
crux_macros = "0.4.2"

## Data processing
arrow = { version = "54.0.0", features = [ "prettyprint" ] }
datafusion = "44.0.0"

## GPU
# TODO

## Scripting
rhai = "1.19.0"

## Written in Rust TODO
# bat
# broot
# exa = { version = "0.10.1", optional = true } # TODO P3 review conflicts
# gping = "1.17.3" # not a lib
# just = { version = "1.36.0", optional = true } # TODO
# lsd
# roogle # not a lib
# ruff # not a lib
# rui = "0.6.1" # experimental at this point
# rustdesk = { version = "0.1.1", optional = true } # app
# xsv = "0.13.0" # not a lib
# zed  # the `zed` crate is not the editor

## General
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
