[package]
name = "database_implementations"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Examples for interacting with various database backends like Sled, SurrealDB, and Meilisearch."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["database", "sled", "surrealdb", "meilisearch", "tantivy", "persistence"]
categories = ["database-implementations"]
publish.workspace = true
autolib = false

[features]
# default = []
meilisearch = ["dep:meilisearch-sdk"]
sled = ["dep:sled"]
surrealdb = ["dep:surrealdb"]
tantivy = ["dep:tantivy"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }

## General
anyhow = "1.0.102"
meilisearch-sdk = { version = "0.33.0", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
sled = { version = "0.34.7", optional = true }
surrealdb = { version = "3.0.5", features = ["kv-mem"], optional = true }
tantivy = { version = "0.26.1", optional = true }
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread"] }
