[package]
name = "text_processing"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - text_processing"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["text_processing"]
publish.workspace = true

[dependencies]
concat-string = "1.0.1"
fancy-regex = "0.14.0"
joinery = "3.1.0"
regex = "1.11.1"
unicode-segmentation = "1.12.0"

## General
anyhow = "1.0.95"
lazy_static = "1.5.0"
once_cell = "1.20.2"
