[package]
name = "aerospace_unmanned_aerial_vehicles"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - aerospace_unmanned_aerial_vehicles"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["aerospace_unmanned_aerial_vehicles"]
publish.workspace = true

[dependencies]

## General
#anyhow = "1.0.95"
