[package]
name = "config"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - config"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["config"]
publish.workspace = true
autolib = false

[dependencies]
config = "0.15.6"
confy = "1.0.0"
# dotenv is outdated, replaced by dotenvy
dotenvy = "0.15.7"
envy = "0.4.2"

## General
anyhow = "1.0.95"
clap = { version = "4.5", features = [ "cargo" ] }
serde = { version = "1.0.217", features = ["derive"] }
