[package]
name = "config"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - config"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["config"]
publish.workspace = true
autolib = false

[dependencies]
# The config package has the same name than the current crate,
# thus we rename it to config1
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
config1 = { version = "0.15.6", package = "config" }
confy = "0.6.1"
# dotenv = "0.15.0" # outdated, replaced by dotenvy
dotenvy = "0.15.7"
envy = "0.4.2"
lexopt = "0.3.0"

## General
anyhow = "1.0.95"
serde = { version = "1.0.217", features = ["derive"] }
serde_derive = "1.0.217"
