[package]
name = "clean"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A very simnple tool to clean `temp` folders before and after testing."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "MIT OR Apache-2.0"
keywords = ["cleanup before / after testing"]
categories = ["development-tools", "command-line-utilities"]
publish = false

[dependencies]
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
walkdir.workspace = true

[[bin]]
name = "clean"
path = "src/main.rs"
