[package]
name = "no_std_no_alloc"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - no_std_no_alloc"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "no_std_no_alloc" ]
publish.workspace = true
autolib = false

[dependencies]
# [add deps](https://github.com/john-cd/rust_howto/issues/1260)
