[package]
name = "wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - wasm"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["wasm"]
publish.workspace = true

[dependencies]
js-sys = "0.3.77"
wasmer = "5.0.4"
wasmtime = "30.0.2"
yew = { version = "0.21.0", features = ["csr"] }

## General
anyhow = "1.0.95"

[features]
#default = []
#wasm = ["dep:wasmer", "dep:wasmtime", "dep:yew"]
