[package]
name = "database"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - database"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "database" ]
publish.workspace = true

[dependencies]
## Database and friends
cornucopia = "0.9.0"
deadpool = "0.12.1"
deadpool-postgres = { version = "0.14.1", features = [
    "serde",
] }
diesel = { version = "2.2.6", features = ["sqlite"] }
diesel_migrations = { version = "2.2.0", features = ["sqlite"] }
elasticsearch = "8.17.0-alpha.1" # NOTE: alpha version
mongodb = "3.1.1"
postgres = "0.19.9"
redis = "0.28.0"
rusqlite = "0.32.1" # pinned
sea-orm = "1.1.3"
seaography = "1.1.2"
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite", "macros" ] }
tokio-postgres = "0.7.12"

## General
anyhow.workspace = true
#axum = "0.8.1"
config = "0.15.3"
dotenvy = "0.15.7"
serde.workspace = true
#serde_json.workspace = true
tokio.workspace = true
