[package]
name = "playground"
version = "0.1.2"
authors = ["John CD"]
edition = "2024"
rust-version = "1.90"
description = "A scratchpad for work-in-progress code snippets and experimental Rust patterns."
documentation = "https://docs.rs/rust_howto/"
homepage = "https://john-cd.com/rust_howto/"
repository = "https://github.com/john-cd/rust_howto/playground/"
keywords = ["experimental", "playground", "wip", "snippets"]
categories = ["development-tools"]
publish = false

[dependencies]
anyhow = "1.0.102"
