[package]
name = "efghijkl"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories.workspace = true
publish = false
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

## The dependencies that are NOT USED (YET) in examples are marked `optional = true`,
## in order to keep the compile speed decent.
## Remove the optional flag as needed.
[dependencies]

## Email
lettre = "0.11.10"

## Embedded
# embassy = { version = "0.0.0", optional  = true } # TODO P1 review installation / required dependencies

## Emulators

## Encoding
base64 = "0.22.1"
byteorder = "1.5.0"
data-encoding = "2.6.0"
form_urlencoded = { version = "1.2.1", optional = true }
monostate = { version = "0.1.13", optional = true }
percent-encoding = "2.3.1"
serde_json = "1.0.132"
toml = "0.8.19"

## External FFI

## Filesystem
glob = "0.3.1"
globset = { version = "0.4.15", optional = true }
memmap2 = "0.9.5"
notify = "7.0.0"
open = { version = "5.3.0", optional = true }
remove_dir_all = { version = "1.0.0", optional = true }
same-file = "1.0.6"
# tempdir = "0.3.7" # outdated, replaced by tempfile
tempfile = "3.14.0"
walkdir = "2.5.0"

## Finance
# RustQuant = { version = "0.3", optional = true }

## Game and friends
bevy = { version = "0.15.0", optional = true }

## Graphics

## GUI
cosmic-text = { version = "0.12.1", optional = true }
# druid = { version = "0.8.3", optional = true } # TODO P3 review conflicts
egui = { version = "0.30.0", optional = true }
# floem = { version = "0.1.1", optional  = true } # TODO P3 review requirements
iced = { version = "0.13.1", optional = true }
leptos = { version = "0.7.0-gamma3", optional = true }
r3bl_tuify = { version = "0.2.0", optional = true }
ratatui = "0.29.0"
slint = { version = "1.8.0", optional = true }
tauri = { version = "2.0.6", optional = true } # requires multiple libraries. See Dockerfile
# xilem = { version = "0.1.0", optional = true } # TODO P3 review prerequisites

## Hardware
num_cpus = "1.16.0"

anyhow = "1.0.94"
csv = "1.3.1"
serde = "1.0.216"
url = "2.5.4"

## Internationalization

## Localization

[features]

## Dependencies that are CURRENTLY unused in the examples (marked as optional above)
## You may check for conflicts with: cargo build --features unused or cargo build --all-features
unused = [
    "dep:bevy",
    "dep:cosmic-text",
    "dep:egui",
    "dep:form_urlencoded",
    "dep:globset",
    "dep:iced",
    "dep:leptos",
    "dep:monostate",
    "dep:r3bl_tuify",
    "dep:remove_dir_all",
    #"dep:RustQuant",
    "dep:slint",
    "dep:tauri",
]
