[package]
name = "computer_vision"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - computer_vision"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["computer_vision"]
publish.workspace = true

[dependencies]
rand.workspace = true # use beta

[target.'cfg(target_os = "linux")'.dependencies]
## Computer vision
image = "0.25.5"
opencv = { version = "0.94.1", features = [
    "clang-runtime",
] } # requires `libopencv-dev` `clang` `libclang-dev`
