name: Build tools on Linux

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tools/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'tools/**'
  workflow_dispatch:

concurrency:
  group: "tools"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout (clones the Git repository)
      uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Build local-tool-builder image
      run: |
        docker buildx build \
          --file .devcontainer/Dockerfile \
          --target local-tool-builder \
          --tag rust_howto_tools_app_builder:latest \
          --cache-from type=gha,scope=rust_howto_tools \
          --cache-to type=gha,mode=max,scope=rust_howto_tools \
          --load ..

    - name: Run tools tests inside container
      run: |
        docker run --rm rust_howto_tools_app_builder:latest bash -lc "cd /code/tools && cargo +nightly test --locked --all-features"
