name: Build `mdbook` preprocessor

on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

concurrency:
  group: "proc"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks out your repository under $GITHUB_WORKSPACE
    - name: Code checkout (clones the Git repository)
      uses: actions/checkout@v4
    - name: Cache Cargo registry and dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          /usr/local/cargo/bin/
          /usr/local/cargo/registry/index/
          /usr/local/cargo/registry/cache/
          /usr/local/cargo/git/db/
          mdbook-scrub/target/
          target/
        key: mdbook-scrub-${{ runner.os }}-cargo-${{ hashFiles('mdbook-scrub/Cargo.lock') }}
        restore-keys: |
          mdbook-scrub-${{ runner.os }}-cargo-
    - name: Install binstall
      run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - name: Install nextest
      run: cargo binstall --no-confirm --secure cargo-nextest
    - name: Install mdBook
      run: cargo binstall --version "0.4.35" --no-confirm mdbook
    - name: Install just
      run: cargo binstall --no-confirm just
    - name: Install nightly Rust
      run: |
        rustup toolchain install nightly
        rustup component add rustfmt clippy --toolchain nightly
        rustup default nightly
    - name: Check the format
      run: just proc f --check
    - name: Build
      run: just proc ba
    - name: Clippy
      run: just proc ca
    - name: Run tests
      run: just proc nta
