[package]
name = "os"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Book code examples and their crate dependencies - os"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

keywords = ["patterns", "cookbook", "howto", "how-to", "documentation", "Rust bible"]
categories = ["os"]
publish.workspace = true
autolib = false

[dependencies]
anyhow = "1.0.100"
libc = "0.2.177"
regex = "1.12.2"
which = "8.0.0"
