[package]
name = "cryptography_cryptocurrencies"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - cryptography_cryptocurrencies"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "cryptography_cryptocurrencies" ]
publish.workspace = true
autolib = false

[dependencies]
# LATER
