[package]
name = "proc_macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "MIT OR Apache-2.0"
keywords.workspace = true
categories = ["development-tools::procedural-macro-helpers"]
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0.41"
syn = { version = "2.0.108", features = ["full"] } # "full" feature is often needed for parsing various Rust constructs
