[package]
name = "proc_macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] } # "full" feature is often needed for parsing various Rust constructs
quote = "1.0"
# FIXME
# proc-macro2 = "1.0" # TokenStream manipulation
